### ISSUE TITLE
Updating TLS code points for BIKE?

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-provider#111]
With https://github.com/open-quantum-safe/liboqs/pull/1369 landed, not entirely unexpected, BIKE doesn't interoperate any more in TLS1.3 with test.openquantumsafe.org (and has no code point for bikel5).
This issue is to document the question & decision whether and to which value(s) to update the code points for these algorithms.
@dstebila @dkostic @christianpaquin @crockeea : Do you have any code points already defined for BIKE(-R4)-L1...5 or shall I simply chose the "next free" ones? Retaining the current ones I'd consider a suboptimal choice, but I'm open to any suggestion.

**Comment by dstebila** [comment]
I don't have any code points already identified. Perhaps there are some already selected for Amazon's s2n?
