### ISSUE TITLE
Error: signature algorithms with excessive message size

### ISSUE THREAD

**Issue by VeronikaNguyen** [open-quantum-safe/oqs-provider#121]
When trying to run TLS with the signature algorithms `sphincssha256128frobust`, `sphincsharaka128frobust`, `sphincsharaka128fsimple`, `sphincsshake256128fsimple`, I get the following errors.
Server error: 
```
7C240000:error:0A000417:SSL routines:ssl3_read_bytes:ssl/tls alert illegal parameter:ssl\record\rec_layer_s3.c:839:SSL alert number 47
```
Client error:
```
142B0000:error:0A000098:SSL routines:read_state_machine:excessive message size:ssl\statem\statem.c:648:
```

Some further comments:
- I double-checked if the algorithms above were enabled by liboqs and indeed they are. 
- TLS works with `sphincssha256128ssimple` and the other enabled signature algorithms.

I debugged into the openssl library. 
In `statem.c`:
```
            if (s->s3.tmp.message_size > max_message_size(s)) {
                SSLfatal(s, SSL_AD_ILLEGAL_PARAMETER,
                         SSL_R_EXCESSIVE_MESSAGE_SIZE);
                return SUB_STATE_ERROR;
            }
```
`max_message_size(s)` is set by `SSL3_RT_MAX_PLAIN_LENGTH = 16384`. However,  `s->s3.tmp.message_size` is larger than `16384` this resulting in the `SSLfatal` error.

**Comment by baentsch** [comment]
Yes. This reminds me of https://github.com/openssl/openssl/issues/10512#issuecomment-1263184329: As you also point out, this is an OpenSSL `master` (constants) issue. Let's raise it there: Do you want to do this or shall I, e.g., referencing my statement made in September:

> My suggestion would be to defer this until this issue is closed, though.

?

**Comment by VeronikaNguyen** [comment]
Thanks for the fast reply and pointer to [https://github.com/openssl/openssl/issues/10512#issuecomment-1263184329](https://github.com/openssl/openssl/issues/10512#issuecomment-1263184329). I will open an issue in OpenSSL `master` and reference your comment there.
