### ISSUE TITLE
Review IDs

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-provider#126]
In preparation for the IETF hackathon (and the next release), this issue is to check all algorithm IDs are in line with recent `liboqs` code updates:
- Falcon (see #125)
- BIKE (see #116)

Anything else? @bhess @xvzcf @dstebila : Did we really only update these two algorithms (breaking KATs/requiring TLS ID changes) since the last Hackathon in November 2022? (period of interest since last interop test added)

**Comment by bhess** [comment]
> Anything else? @bhess @xvzcf @dstebila : Did we really only update these two algorithms (breaking KATs/requiring TLS ID changes)?

Wasn't there a SPHINCS+ update changing the PRF from SHA256 to SHA512?

**Comment by baentsch** [comment]
> Wasn't there a SPHINCS+ update changing the PRF from SHA256 to SHA512?

Can you point to a PR? When glancing over last year's PRs, there's nothing with the label "sphincs" standing out...

**Comment by bhess** [comment]
Ah ok, the PR with the change isn't merged yet: https://github.com/open-quantum-safe/liboqs/pull/1420

**Comment by baentsch** [comment]
Closing the issue given we have now tagged an `ietf116` version and everyone had a chance to speak up :) Thanks, @bhess for the sanity check.
