### ISSUE TITLE
qsc_encodings silently failing

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-provider#129]
**Describe the bug**
The CI tests show error messages like "Could not create OQS signature encoding algorithm draft-uni-qsckeys-falcon-00/sk-pk (Falcon-512, 1.3.9999.3.6). Defaulting to no encoding."

**To Reproduce**
See for example https://app.circleci.com/pipelines/github/open-quantum-safe/oqs-provider/410/workflows/a97aa465-7023-4479-89e0-844fcb926e7f/jobs/431 (scroll to last test sequence and check logfiles).

**Expected behavior**
The tests should fail and not pass -- otherwise they don't have value, right @bhess?

**Environment (please complete the following information):**
CircleCI

Update/add: I cannot reproduce this behaviour locally, so here's at least a screenshot:
![grafik](https://user-images.githubusercontent.com/57787676/227712916-6721cc65-59e0-4dc1-921f-6ae64520909b.png)

**Comment by bhess** [comment]
I agree, the tests should fail. I created a fix in PR #131. Thanks for noticing!
