### ISSUE TITLE
Improve qsc encoder integration

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-provider#130]
Build time for oqs-provider significantly deteriorated when qsc-encoder integration was done. A glance at disk usage shows the problem vividly: The `src` of qsc-`encoder` is more than 2x as large as all of OpenSSL, 3x the size of a fully built `liboqs` and thus roughly 60% of a complete `oqs-provider` build (incl. opensslv3 binaries and libraries):

![grafik](https://user-images.githubusercontent.com/57787676/227711692-1a39c80b-b05b-4bb9-9f81-8843718b057b.png)

--> Is it really necessary to add KATs for all algorithms (again)? That alone seems to be 255MBytes. Then there's PPTX files and huge `.git` index files: The latter are 38x larger in qsc-encoder than in all of oqs-provider (3.5MB vs 138MB).

@bhess: Do you agree that this is not OK and have time to remedy this?

**Comment by bhess** [comment]
Yes the repo was quite large due to the KAT and unrelated files. I now created a separate smaller repository containing only the library. See PR #131.
