### ISSUE TITLE
Update qsc encoder

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-provider#133]
RFC seems to be at version 01 (https://datatracker.ietf.org/doc/draft-uni-qsckeys/01/) while encoding supported seems to be at level "00". Not aware whether this has a functional difference, but the [available encoding strings](https://github.com/open-quantum-safe/oqs-provider/blob/main/ALGORITHMS.md#key-encodings) thus appear stale.

**Comment by bhess** [comment]
draft-uni-qsckeys(-01) is outdated and was split to individual drafts draft-uni-qsckeys-dilithium(-00), draft-uni-qsckeys-sphincsplus(-00), ...

I don't think a reference to the old draft is needed.
