### ISSUE TITLE
Remove dependency on internal OpenSSL test harness

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-provider#137]
Some tests depend on [ssltestlib](https://github.com/openssl/openssl/blob/master/test/helpers/ssltestlib.c), an OpenSSL internal test library. This dependency causes issues when testing in a setup without this code present (non-master source, binary-only).

This issue is to suggest removing this dependency and to develop independent tests providing similar functionality.

**Comment by mouse07410** [comment]
Perhaps, just copying `test/helpers/ssltestlib.c` to this repo with the appropriate patch...? it does seem to include some internal headers though...

**Comment by baentsch** [comment]
Yup -- it has many (internal) dependencies -- that further change between versions. Not in option in my eyes. Testing using just the official, external OpenSSL APIs surely is possible -- just "a bit of work"... :)
