### ISSUE TITLE
Re-enable offline build

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-provider#139]
The qsc-encoder integration requires an online connection even when only running `make`. This disables the possibility to develop code when offline. 

Is this something easily remedied, @bhess? If not, would you mind I set USE_ENCODING_LIB=OFF by default?

Also, what happens in case of a release? Will all required code be included or will this online dependency be permeated into a ZIP file?

**Comment by bhess** [comment]
> The qsc-encoder integration requires an online connection even when only running `make`. This disables the possibility to develop code when offline.
> 
> Is this something easily remedied, @bhess?

Yes this is easy by adding a `UPDATE_DISCONNECTED 1` to the cmake `ExternalProject_Add`. This way no update will be attempted on `make`. I'll add it to #131.

> Also, what happens in case of a release? Will all required code be included or will this online dependency be permeated into a ZIP file?

How is it done with other dependencies (e.g. liboqs), are they included in the release? I'd follow the the same procedure with the encoder lib.

**Comment by baentsch** [comment]
Fixed by #131
