### ISSUE TITLE
Document -DCLOUDFLARE

### ISSUE THREAD

**Issue by wbl** [open-quantum-safe/oqs-provider#141]
Currently the OpenQuantumSafe provider has a compilation option that supposedly creates the x25519+Kyber768 combination with some codepoint.

This is not documented anywhere: either the effects or how to pass it to the build scripts.

**Comment by baentsch** [comment]
As we consider this combination illogical (and weak, in the sense that algorithms of different strengths are mixed) and thus goes against `oqsprovider`s internal logic of building hybrids we only created this for interop testing (where it works) but not for "everyday" use. We'll surely change this (and document it for "everyone's use") if there'd be a move to standardize (say an RFC draft) for this combination. 

Until then, please see https://github.com/open-quantum-safe/oqs-provider/pull/78 containing all information how to build and use.

**Comment by dstebila** [comment]
Is this obsoleted by #177?

**Comment by baentsch** [comment]
> Is this obsoleted by #177?

Yes, #177 enabled the weak cloudflare hybrids (bit_security=128) by default.
