### ISSUE TITLE
[Windows] Running tests

### ISSUE THREAD

**Issue by mingw-io** [open-quantum-safe/oqs-provider#142]
Windows 10 x64
Branch: master/main
Built from source

![image](https://user-images.githubusercontent.com/70483213/230613636-7710ae68-ddc0-4678-9c44-0690fd3e3920.png)

All tests pass except 'oqs_test_kems'.

![image](https://user-images.githubusercontent.com/70483213/230613679-e16b01fb-2cdb-4c6a-afc5-c14e67873396.png)

We have tried setting up some environment variables (e.g. OQSENC) to no avail.

Thanks in advance.

**Comment by baentsch** [comment]
> All tests pass 

Thanks for the good news...

> except 'oqs_test_kems'.

...OK, one cannot have it all :-) The error is really weird, deep down in the EC logic: Never saw that. 

Same question as last time: Any chance you can share scripts to re-build on our side? Also very welcome would be a CI script for Windows testing via PR.

> We have tried setting up some environment variables (e.g. OQSENC) to no avail.

This would only work with a Debug build: Did you build one?
