### ISSUE TITLE
security bits=-1

### ISSUE THREAD

**Issue by cryptobsv** [open-quantum-safe/oqs-provider#145]
I have generated a CA and a host certificate, both with sig algo dilithium5. When I start `openssl s_server` with option `-security_debug_verbose` I get:

    Using default temp DH parameters
    Security callback: Certificate chain EE key=, bits=256, security bits=256: yes
    Security callback: Certificate chain CA digest=dilithium5, security bits=-1: no
    error setting certificate
    802BF3F4147F0000:error:0A00018E:SSL routines:SSL_CTX_use_certificate:ca md too weak:ssl/ssl_rsa.c:221

The certs look ok to me. I have tried this with falcon512 and with the branches `main` and `ossl-sigload`. I have straced `openssl` and verified that `oqs-provider` is being loaded. Probably, I am doing something wrong, but I have no idea what. Thanks!

**Comment by baentsch** [comment]
With near certainty you are using an old OpenSSL Code base. Full signature provider Support only exists in OpenSSL Master. Please let us know if the failure persists if you're using Master.

**Comment by baentsch** [comment]
@cryptobsv Please share the output of `openssl version` and `openssl list -providers` to see whether my hunch above is correct. And/or please retry your test in the docker image at `openquantumsafe/oqs-ossl3`.

**Comment by cryptobsv** [comment]
Yes, your hunch above was correct. I thought any openssl 3.x would do and picked 3.0.8 to work with a well-defined version. Moving to master solved this problem. Thanks again for the quick and helpful support!
