### ISSUE TITLE
Key import is nonfunctional

### ISSUE THREAD

**Issue by distorted-mdw** [open-quantum-safe/oqs-provider#148]
The short version is: `oqsx_key_fromdata` is missing a call to `oqsx_key_set_composites`.  Without this, the `comp_privkey` and `comp_pubkey` vectors are left unitialized, which could lead to all sorts of bad things, though I ended up debugging this as a result of mysterious signature verification failures.

Two-line MR on its way.

**Comment by baentsch** [comment]
Same question as in #149: Can you please provide a (bug) reproducer?
