### ISSUE TITLE
Generate (O)ID tables

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-provider#157]
Generate tables replacing https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/oqs-template/oqs-kem-info.md and https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/oqs-template/oqs-sig-info.md as part of the code generation using https://github.com/open-quantum-safe/oqs-provider/blob/main/oqs-template/generate.py.

**Comment by dstebila** [comment]
I think it would be good if we did archive the IDs we used in TLS, even if we're no longer using that ID.  At least we should have that information somewhere publicly.  Whether it's in the oqs-provider repo or the OpenSSL-111 repo.

A simple solution could be to manually add the old lines that are no longer being generated to an appendix at the end, if need be.
