### ISSUE TITLE
Algorithm updates: Documentation to be retained?

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-provider#163]
Looking at https://github.com/open-quantum-safe/oqs-provider/compare/main...open-quantum-safe:oqs-provider:update-algs?expand=1 it seems we could do a PR to bring oqs-provider in sync with liboqs again. However, all "old" algorithms in `generate.yml` got removed. Why?

Key question (I guess to @dstebila ): Do we want to retain (the ability to generate) "old" (O)IDs? If no, we can also close 
 https://github.com/open-quantum-safe/oqs-provider/issues/157. If Yes, @xvzcf please bring back the work done as part of https://github.com/open-quantum-safe/oqs-provider/pull/158.

**Comment by mouse07410** [comment]
> Key question (I guess to @dstebila ): Do we want to retain (the ability to generate) "old" (O)IDs?

I say "no, we don't".

**Comment by baentsch** [comment]
Closed by #167
