### ISSUE TITLE
CMS signing fails (Openssl is not able to use oqsprovider) if CMS_NOATTR is specified in CMS_add1_signer

### ISSUE THREAD

**Issue by kamlesh0hrs** [open-quantum-safe/oqs-provider#169]
Openssl is not using oqsprovider for CMS signing if CMS_NOATTR is provided in CMS_add1_signer. It fails in CMS_final.

I back ported the patch ( https://github.com/openssl/openssl/pull/17733 ) to openssl-3.0.8. Normal CMS sign/verify is working fine.
But if I use CMS_NOATTR flag openssl is not using oqsprovider for signing.

To reproduce it just write a C code for CMS signing using openssl C apis and try to  do CMS signing.

        cms = CMS_sign(NULL, NULL, NULL, NULL,
                   CMS_NOCERTS | CMS_PARTIAL | CMS_BINARY |
                   CMS_DETACHED | CMS_STREAM);
        ERR(!cms, "CMS_sign");

        ERR(!CMS_add1_signer(cms, x509, private_key, digest_algo,
                     CMS_BINARY|CMS_NOCERTS|CMS_NOSMIMECAP |CMS_NOATTR),
            "CMS_add1_signer");

        ERR(CMS_final(cms, bm, NULL, CMS_NOCERTS | CMS_BINARY) < 0,
            "CMS_final");
------

liboqs - 0.7.2
oqsprovider - 0.4.0
openssl - 3.0.8

This issue might be something to report in openssl but knowing that OQS dev team has provided the patch I am reporting it here.

Thanks,
Kamlesh

**Comment by baentsch** [comment]
Thanks for giving this a try -- and even backporting a PR to (try to) enable this feature in OpenSSL 3.0! This clearly is no oqsprovider issue, but one for OpenSSL. However, please note that the OpenSSL core team has repeatedly stated that provider-based signature capabilities are _not_ a (supported) feature of OpenSSL 3.0 and hence, nothing to support `oqsprovider` in delivering this will ever make its way back into OpenSSL 3.0 (or 3.1) for all I know. 

So, what's stopping you from using the latest code from OpenSSL (3.2-dev), oqsprovider (0.5-dev) and liboqs (0.8-dev) instead? CMS (and lots more for PQC) works there.

**Comment by kamlesh0hrs** [comment]
Thanks @baentsch for the quick reply! 

Yes, I will give it a try with openssl-3.2-dev.

Thanks,
Kamlesh

**Comment by kamlesh0hrs** [comment]
With OpensSSL - 3.2 (dev)
         liboqs - 0.8-dev
         oqsprovider - 0.5-dev

CMS signing is working fine with CMS_NOATTR. I am closing this issue.
Thanks @baentsch !
