### ISSUE TITLE
MacOS: fails to find liboqs

### ISSUE THREAD

**Issue by mouse07410** [open-quantum-safe/oqs-provider#171]
**Describe the bug**
Tests should - but do not - look in `/opt/local/lib` for libraries like `liboqs.dylib`.

```text
LD_LIBRARY_PATH=/Users/ur20980/src/oqs-provider/.local/lib64
OPENSSL_APP=/opt/local/libexec/openssl3/bin/openssl
OPENSSL_CONF=/opt/local/libexec/openssl3/etc/openssl/openssl.cnf
OPENSSL_MODULES=/opt/local/libexec/openssl3/lib/ossl-modules
Version information:
OpenSSL 3.1.0 14 Mar 2023 (Library: OpenSSL 3.1.0 14 Mar 2023)
list: unable to load provider oqsprovider
Hint: use -provider-path option or OPENSSL_MODULES environment variable.
40664950F87F0000:error:12800067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:118:filename(_build/lib/oqsprovider.dylib): dlopen(_build/lib/oqsprovider.dylib, 0x0002): Library not loaded: @rpath/liboqs.3.dylib
  Referenced from: <DE45930A-2ABF-3032-BFF3-19F96D0064A6> /Users/ur20980/src/oqs-provider/_build/lib/oqsprovider.0.5.0-dev.dylib
  Reason: tried: '/usr/local/lib/liboqs.3.dylib' (no such file), '/usr/lib/liboqs.3.dylib' (no such file, not in dyld cache)
40664950F87F0000:error:12800067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:152:
40664950F87F0000:error:07880025:common libcrypto routines:provider_init:reason(524325):crypto/provider_core.c:904:name=oqsprovider
Baseline openssl invocation failed. Exiting test.
```

`LD_LIBRARY_PATH` is not an answer, because (a) MacOS uses `DYLD_LIBRARY_PATH` and ignores `LD_LIBRARY_PATH`, and (b) setting that env var would limit where the loader searches for missing libraries, i.e., we'd risk that it would now find what's in `$DYLD_LIBRARY_PATH` but stops finding what's not there.

**To Reproduce**
See above.

**Expected behavior**
Tests passing, with all the relevant libraries located correctly.

**Screenshots**

**Environment (please complete the following information):**
 - OS: MacOS Ventura 13.4
 - OpenSSL version: 3.2.0-dev and 3.1.0

**Comment by baentsch** [comment]
Hmm -- my original intention was to have `oqsprovider` be a self-contained executable, not referencing `liboqs` with unresolved symbols leading to problems like this (and having to ship several executables). When looking at the OSX binary with `otool` I'm also not seeing such dependencies to other .dylibs. Same on Linux: No `liboqs` reference:

```
ldd oqsprovider.so
	linux-vdso.so.1 (0x00007ffe099f2000)
	libcrypto.so.3 => /home/mib/git/oqs/oqs-provider/.local/lib64/libcrypto.so.3 (0x00007fdc3dbd9000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdc3d7e8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fdc3eae7000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fdc3d5e4000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdc3d3c5000)
```

So, what did you do to achieve this dependency? Build `liboqs` shared and link `oqsprovider` against that?

**Comment by mouse07410** [comment]
> So, what did you do to achieve this dependency? Build `liboqs` shared and link `oqsprovider` against that?

Certainly. All of my libraries are built shared.

**Comment by baentsch** [comment]
> Certainly. All of my libraries are built shared.

This information definitely is helpful to reproduce things -- most likely also on Linux.... Please specify how exactly you invoke `cmake` when building both `oqsprovider` as well as `liboqs`.

> setting that env var would limit where the loader searches for missing libraries, i.e., we'd risk that it would now find what's in $DYLD_LIBRARY_PATH but stops finding what's not there.

Do I understand this right to mean you do not want to set DYLD_LIBRARY_PATH to find `liboqs.dyld`? And further you also do not want to install `liboqs` in a system location (searched when not explicitly using (DY)LD_LIBRARY_PATH)? At least in Linux (no idea whether that works in OSX), other than using [LDFLAGS](https://cmake.org/cmake/help/v3.26/envvar/LDFLAGS.html) with a path "hint" at build time I wouldn't know how to resolve that quandary....

**Comment by baentsch** [comment]
> > Certainly. All of my libraries are built shared.
> 
> This information definitely is helpful to reproduce things -- most likely also on Linux.... Please specify how exactly you invoke `cmake` when building both `oqsprovider` as well as `liboqs`.

May the answer to this also have a reading on https://github.com/openssl/openssl/issues/21023 ? It seems `python` uses one way to decide which libraries to load (that one apparently cannot control) and your build of `liboqs` (test programs) uses another (that one can control). It of course still is not "ideal" that different `libcrypto` versions trigger crashes....

**Comment by mouse07410** [comment]
> Please specify how exactly you invoke `cmake` when building both `oqsprovider` as well as `liboqs`.

For `liboqs`:

```text
if [[ "$1" == "no-opt" ]]; then
    echo "Building Reference (unoptimized) liboqs..."
    OPT="-DOQS_DIST_BUILD=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Debug"
    CFLAGS="-g -O0 -std=gnu18 -march=native -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
    CMAKE_C_FLAGS="$CFLAGS"
else
    echo "Building Optimized liboqs..."
    OPT="-DOQS_DIST_BUILD=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release"
    CFLAGS="-g -O3 -std=gnu18 -march=native -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
    CMAKE_C_FLAGS="$CFLAGS"
fi

env RUN_TESTS_PARALLEL_UPPER=FALSE cmake -GNinja .. -DOQS_USE_OPENSSL=ON ${OPT} -DCMAKE_INSTALL_PREFIX=/opt/local

# Build
ninja

time ninja run_tests
```

For `oqsprovider`:
```bash
#!/bin/bash

# Cleaning up previous builds
make clean
rm -rf tmp/*
rm -f interop.log interop-3.log

# Set env var - flags
OQSPROV=1
OQSKM=1
OQSKEY=1

unset OPENSSL_INSTALL

# Build for local sources of master branch of OpenSSL-3.2+
if [ -d $HOME/openssl-3 ]; then
    rm -rf _build
    DYLD_LIBRARY_PATH="$HOME/openssl-3/lib:/usr/local/lib:"
    OPENSSL_ROOT_DIR="$HOME/openssl-3"
    OPENSSL_DIR="$OPENSSL_ROOT_DIR"
    OPENSSL_INSTALL="$OPENSSL_DIR"
    OPENSSL_APP="$OPENSSL_ROOT_DIR/bin/openssl"
    OPENSSL="$OPENSSL_APP"
    OPENSSL_CONF="$OPENSSL_ROOT_DIR/etc/openssl.cnf"
    OPENSSL_MODULES="$OPENSSL_ROOT_DIR/lib/ossl-modules"
    OPENSSL_LIB_DIR="$OPENSSL_ROOT_DIR/lib"
    OPENSSL_INCLUDE_DIR="$OPENSSL_ROOT_DIR/include"
	echo "Building for source-based OpenSSL-3.2.x-dev..."
	env | grep OPENSSL > build-out-s.txt
    echo "" >> build-out-s.txt
	cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_ENCODING_LIB=OFF -DOPENSSL_ROOT_DIR="$HOME/src/openssl" -DCMAKE_C_FLAGS="$CFLAGS -I${OPENSSL_INCLUDE_DIR} -I/opt/local/include -L${OPENSSL_LIB_DIR} -L/opt/local/lib" -DCMAKE_VERBOSE_MAKEFILE:BOOL=True -S . -B _build 2>&1 | tee -a build-out-s.txt
	cmake --build _build 2>&1 | tee -a build-out-s.txt
	if [ -x _build/lib/oqsprovider.0.5.0-dev.dylib ]; then
		echo "Successful build for source-based OpenSSL"
		scripts/runtests.sh 2>&1 | tee tests-out-s.txt
		cp _build/lib/oqsprovider.0.5.0-dev.dylib "$OPENSSL_MODULES"
	else
		echo "Apparently, building for source-based OpenSSL-3.2.x-dev failed"
		echo ""
	fi
else
	echo ""
	echo "Sources of OpenSSL-3.2.x-dev not found, skipping..."
	echo ""
fi

# Build for Macports-installed binaries of OpenSSL-3.+
if [ -d /opt/local/libexec/openssl3 ]; then
    rm -rf _build
    LD_LIBRARY_PATH="/opt/local/lib:/usr/local/lib:"
    OPENSSL_ROOT_DIR="/opt/local/libexec/openssl3"
    OPENSSL_DIR="$OPENSSL_ROOT_DIR"
    OPENSSL_INSTALL="$OPENSSL_DIR"
    OPENSSL_APP="$OPENSSL_ROOT_DIR/bin/openssl"
    OPENSSL="$OPENSSL_APP"
    OPENSSL_CONF="$OPENSSL_ROOT_DIR/etc/openssl/openssl.cnf"
    OPENSSL_MODULES="$OPENSSL_ROOT_DIR/lib/ossl-modules"
    OPENSSL_LIB_DIR="$OPENSSL_ROOT_DIR/lib"
    OPENSSL_INCLUDE_DIR="$OPENSSL_ROOT_DIR/include"
    env | grep OPENSSL > build-out.txt
    echo "" >> build-out.txt
	echo "Building for Macports-installed OpenSSL-3..."
	cmake -DCMAKE_BUILD_TYPE=Debug -DOPENSSL_ROOT_DIR="/opt/local/libexec/openssl3" -DCMAKE_C_FLAGS="$CFLAGS -I/opt/local/include -L/opt/local/lib" -DCMAKE_VERBOSE_MAKEFILE:BOOL=True -S . -B _build 2>&1 | tee -a build-out.txt
	echo "" >> build-out.txt
	cmake --build _build 2>&1 | tee -a build-out.txt
	if [ -x _build/lib/oqsprovider.0.5.0-dev.dylib ]; then
		echo "Successful build for Macports-installed OpenSSL"
                # To make the tests run correctly - workaround for double-libcrypto bug
		sudo cp "$HOME"/src/openssl.block.cnf "$OPENSSL_CONF"
		scripts/runtests.sh 2>&1 | tee tests-out.txt
		sudo cp _build/lib/oqsprovider.0.5.0-dev.dylib "$OPENSSL_MODULES"
		sudo cp "$HOME"/src/openssl.cnf "$OPENSSL_CONF"
	else
		echo "Apparently, building for Macports-installed OpenSSL-3 failed"
		echo ""
	fi	
else
	echo ""
	echo "Macports-installed OpenSSL-3 not found, skipping..."
	echo ""
fi

exit 0
```

> May the answer to this also have a reading on https://github.com/openssl/openssl/issues/21023 ?

I don't think so.

**Comment by baentsch** [comment]
Thanks for these scripts. Two questions: 1) For `liboqs` I presume you are also running `ninja install`, i.e. have the shared library reside in `/opt/local(/lib)`? 2) Why are you using/setting `LD_LIBRARY_PATH` for the 3.1.0 install? I thought only DYLD_LIBRARY_PATH works on OSX?

**Comment by mouse07410** [comment]
> For `liboqs` I presume you are also running `ninja install`, i.e. have the shared library reside in `/opt/local/lib`? 

Yes, of course.

> Why are you using/setting `LD_LIBRARY_PATH` for the 3.1.0 install? 

I am not - it was a darn cut-and-paste screw-up. :-(
Thanks for catching it for me.

> I thought only `DYLD_LIBRARY_PATH` works on OSX?

That is correct.

**Comment by mingw-io** [comment]
It seems MacOS suffers from DLL hell symptoms or pathology!

We haven't faced any issues finding/linking liboqs.

> my original intention was to have oqsprovider be a self-contained executable, not referencing liboqs with unresolved symbols leading to problems like this (and having to ship several executables).

![image](https://github.com/open-quantum-safe/oqs-provider/assets/70483213/57afc9e3-c555-4565-864b-6f2687972e11)

**Comment by mouse07410** [comment]
@mingw-io no offense meant, but I don't think you understand the issue discussed here. Perhaps you could hold off your posts - they add nothing useful at the moment, and only increase noise.

**Comment by baentsch** [comment]
> Thanks for catching it for me.

UW. Does the issue persist with "DY" added? That way `liboqs.dylib` should be found also in case of 3.1.0, no?

**Comment by mouse07410** [comment]
> UW. Does the issue persist with "DY" added? That way `liboqs.dylib` should be found also in case of 3.1.0, no?

Yes, same problem:
```text
Test setup:
LD_LIBRARY_PATH=/Users/ur20980/src/oqs-provider/.local/lib64
OPENSSL_APP=/opt/local/libexec/openssl3/bin/openssl
OPENSSL_CONF=/opt/local/libexec/openssl3/etc/openssl/openssl.cnf
OPENSSL_MODULES=/opt/local/libexec/openssl3/lib/ossl-modules
No OQS-OpenSSL111 interop test because of absence of docker
Version information:
OpenSSL 3.1.0 14 Mar 2023 (Library: OpenSSL 3.1.0 14 Mar 2023)
list: unable to load provider oqsprovider
Hint: use -provider-path option or OPENSSL_MODULES environment variable.
4026C65EF87F0000:error:12800067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:118:filename(_build/lib/oqsprovider.dylib): dlopen(_build/lib/oqsprovider.dylib, 0x0002): Library not loaded: @rpath/liboqs.3.dylib
  Referenced from: <88CFE3B7-AB41-305E-AEB4-99624E0D8C53> /Users/ur20980/src/oqs-provider/_build/lib/oqsprovider.0.5.0-dev.dylib
  Reason: tried: '/usr/local/lib/liboqs.3.dylib' (no such file), '/usr/lib/liboqs.3.dylib' (no such file, not in dyld cache)
4026C65EF87F0000:error:12800067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:152:
4026C65EF87F0000:error:07880025:common libcrypto routines:provider_init:reason(524325):crypto/provider_core.c:904:name=oqsprovider
Baseline openssl invocation failed. Exiting test.
Sun May 28 20:36:40 EDT 2023
```

BTW, any reason your test does not print `DYLD_LIBRARY_PATH`?

**Comment by baentsch** [comment]
Now it seems I finally have managed to set up a CI job that mirrors your setup. And it shows the same problematic behaviour: It doesn't seem to load `oqsprovider` probably because it doesn't find `liboqs`:

```
_build/lib/oqsprovider.dylib:
	@rpath/oqsprovider.1.dylib (compatibility version 1.0.0, current version 0.5.0)
	@rpath/liboqs.3.dylib (compatibility version 3.0.0, current version 0.8.0)
	/usr/local/opt/openssl@3/lib/libcrypto.3.dylib (compatibility version 3.0.0, current version 3.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
```

Now I have to admit I know way too little about OSX' specific shared linking behaviour and the meaning of "@rpath". [This](https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/RunpathDependentLibraries.html) seems to imply that libraries built this way will use whichever "rpath" has been set for the loading executable, i.e., `openssl` in our case if I'm right. As we cannot control that, I'm afraid we have to disable the use of "rpath" in a setting such as yours (which is now also ours :-). The way to do this seems to be by way of an OSX-specific `cmake` directive: https://cmake.org/cmake/help/latest/prop_tgt/MACOSX_RPATH.html (setting to false). Agreed? Would you want to try this with your `liboqs` build script, @mouse07410 ? I'm doing this by trial-and-error via a CI VM, taking about 30mins per iteration (See #140.... :-( What beats me though, is how/why `oqsprovider.dylib` is found --- maybe OPENSSL_MODULES opens another avenue for finding/loading libraries... Would it be a possibility to put a softlink to (wherever you installed) `liboqs.dylib` next to the `oqsprovider`? Might this resolve the issue?

**Comment by mouse07410** [comment]
Sure. But my bigger concern is that `DYLD_LIBRARY_PATH` does not seem to be inherited by the `scripts/runtests.sh`. And I don't want to mess with its "global" value by doing something like `export DYLD_LIBRARY_PATH=/opt/local/lib:usr/local/lib:`

**Comment by baentsch** [comment]
> my bigger concern is that DYLD_LIBRARY_PATH does not seem to be inherited by the scripts/runtests.sh

I'm not sure I understand what is meant by "inherited by"?

But whatever, I think I now found a resolution: By passing to the `cmake` invocation for `oqsprovider` the environment variable `liboqs_DIR` one can direct it to properly create a reference to wherever `liboqs` has been placed: https://github.com/open-quantum-safe/oqs-provider/blob/2ba86da572e9ad55d3f23765f8c784036413606f/.circleci/config.yml#LL140C1-L140C22. This does not work when using `-DCMAKE_PREFIX_PATH` (but then again, this is logical as only the former is meant to locate external libraries while the latter defines the install location -- my mistake was to place `liboqs` and `openssl` into the same place which caused the problem to be hidden in the original install scripts). After adapting this in the CI instructions, everything works as desired, regardless where (a shared) `liboqs` has been installed (both positively and negatively tested on an M1 OSX box). 

The reason why things fail for you most likely have to do with the way you build `liboqs`: Your script explicitly passes "CMAKE_C_FLAGS" but no matching instructions for the linker. The approach of using `cmake` mechanisms by way of directing `oqsprovider`s `cmake` to the install location of `liboqs` using the `liboqs_DIR` environment variable directive seems to resolve this, both for include/compile as well as linking instructions.

Thanks for  making me learn quite a bit about OSX, shared libs and installs and `cmake`: This definitely improved how things can be (separately) deployed -- and now also tested -- it just was tedious to do this so "remotely"...

**Comment by mouse07410** [comment]
> >  my bigger concern is that DYLD_LIBRARY_PATH does not seem to be inherited by the scripts/runtests.sh
>
>I'm not sure I understand what is meant by "inherited by"?

I mean that in the following example
```bash
DYLD_LIBRARY_PATH="/opt/local/lib:/usr/local/lib"
scripts/runtests.sh
```
I expect that script `script/runtests.sh` here would know that var `DYLD_LIBRARY_PATH` has value `/opt/local/lib:/usr/local/lib`. While in fact,  `script/runtests.sh` shows no awareness whatsoever of `DYLD_LIBRARY_PATH` and considers it empty.

> But whatever, I think I now found a resolution  .  .  .

Not quite. Your "solution" in the CircleCI seems to be bound to HomeBrew - which I don't find acceptable (not to mention that I use Macports, and Brew is less secure). 

>   .  .  .  using the `liboqs_DIR` environment variable directive seems to resolve  .  .  .

That probably should help - though it depends on how it is used. For MacOS, the surest thing would be to prepend that value to `DYLD_LIBRARY_PATH`. 

> Thanks for making me learn quite a bit about OSX, shared libs and installs and `cmake`: This definitely improved how things can be (separately) deployed -- and now also tested -- it just was tedious to do this so "remotely"...

Always happy to oblige! :-)

**Comment by mouse07410** [comment]
I'm afraid #140 made things worse. Now, in addition to the original problem, it fails to locate `liboqs.3.dylib` for OpenSSL-3.2.0-dev.

To remind: 
- for OpenSSL-3.2.0-dev, `liboqs.3.dylib` resides in `${HOME}/openssl-3/lib/` (provided to `scripts/runtests.sh` in both `DYLD_LIBRARY_PATH` and `OPENSSL_ROOT_DIR`).
- For OpenSSL-3.1.0, `liboqs.3.dylib` resides in `/opt/local/lib/` (provided to `scripts/runtests.sh` in both `DYLD_LIBRARY_PATH` and `OPENSSL_ROOT_DIR`).

And you were talking about `liboqs_DIR` - that's the only potentially needed thing, and I can't find any of your scripts using this var.

**Comment by mouse07410** [comment]
Here's the build script that works for both versions of OpenSSL on MacOS:
```bash
#!/bin/bash

# Cleaning up previous builds
make clean
rm -rf tmp/*
rm -f interop.log interop-3.log

# Set env var - flags
OQSPROV=1
OQSKM=1
OQSKEY=1

unset OPENSSL_INSTALL

set DYLD="${DYLD_LIBRARY_PATH}"

# Build for local sources of master branch of OpenSSL-3.2+
if [ -d $HOME/openssl-3 ]; then
    rm -rf _build
    export DYLD_LIBRARY_PATH="${HOME}/openssl-3/lib:/usr/local/lib:/opt/local/lib:${DYLD}"
    export LD_LIBRARY_PATH="${DYLD_LIBRARY_PATH}"
    OPENSSL_ROOT_DIR="$HOME/openssl-3"
    OPENSSL_DIR="$OPENSSL_ROOT_DIR"
    OPENSSL_INSTALL="$OPENSSL_DIR"
    OPENSSL_APP="$OPENSSL_ROOT_DIR/bin/openssl"
    OPENSSL="$OPENSSL_APP"
    OPENSSL_CONF="$OPENSSL_ROOT_DIR/etc/openssl.cnf"
    OPENSSL_MODULES="$OPENSSL_ROOT_DIR/lib/ossl-modules"
    OPENSSL_LIB_DIR="$OPENSSL_ROOT_DIR/lib"
    OPENSSL_INCLUDE_DIR="$OPENSSL_ROOT_DIR/include"
	echo "Building for source-based OpenSSL-3.2.x-dev..."
	env | grep OPENSSL > build-out-s.txt
    echo "" >> build-out-s.txt
	cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_ENCODING_LIB=OFF -DOPENSSL_ROOT_DIR="$HOME/src/openssl" -DCMAKE_C_FLAGS="$CFLAGS -g -I${OPENSSL_INCLUDE_DIR} -L${OPENSSL_LIB_DIR} " -DCMAKE_VERBOSE_MAKEFILE:BOOL=True -S . -B _build 2>&1 | tee -a build-out-s.txt
	cmake --build _build 2>&1 | tee -a build-out-s.txt
	if [ -x _build/lib/oqsprovider.0.5.0-dev.dylib ]; then
		echo "Successful build for source-based OpenSSL"
		echo "Uri's DYLD_LIBRARY_PATH=\"${DYLD_LIBRARY_PATH}\""
		scripts/runtests.sh 2>&1 | tee tests-out-s.txt
		cp _build/lib/oqsprovider.0.5.0-dev.dylib "$OPENSSL_MODULES"
	else
		echo "Apparently, building for source-based OpenSSL-3.2.x-dev failed"
		echo ""
	fi
else
	echo ""
	echo "Sources of OpenSSL-3.2.x-dev not found, skipping..."
	echo ""
fi

# Build for Macports-installed binaries of OpenSSL-3.+
if [ -d /opt/local/libexec/openssl3 ]; then
    rm -rf _build
    export DYLD_LIBRARY_PATH="/opt/local/lib:/usr/local/lib:${DYLD}"
    export LD_LIBRARY_PATH="${DYLD_LIBRARY_PATH}"
    OPENSSL_ROOT_DIR="/opt/local/libexec/openssl3"
    OPENSSL_DIR="$OPENSSL_ROOT_DIR"
    OPENSSL_INSTALL="$OPENSSL_DIR"
    OPENSSL_APP="$OPENSSL_ROOT_DIR/bin/openssl"
    OPENSSL="$OPENSSL_APP"
    OPENSSL_CONF="$OPENSSL_ROOT_DIR/etc/openssl/openssl.cnf"
    OPENSSL_MODULES="$OPENSSL_ROOT_DIR/lib/ossl-modules"
    OPENSSL_LIB_DIR="$OPENSSL_ROOT_DIR/lib"
    OPENSSL_INCLUDE_DIR="$OPENSSL_ROOT_DIR/include"
    env | grep OPENSSL > build-out.txt
    echo "" >> build-out.txt
	echo "Building for Macports-installed OpenSSL-3..."
	cmake -DCMAKE_BUILD_TYPE=Debug -DOPENSSL_ROOT_DIR="/opt/local/libexec/openssl3" -DCMAKE_C_FLAGS="$CFLAGS -g -I/opt/local/include -L/opt/local/lib" -DCMAKE_VERBOSE_MAKEFILE:BOOL=True -S . -B _build 2>&1 | tee -a build-out.txt
	echo "" >> build-out.txt
	cmake --build _build 2>&1 | tee -a build-out.txt
	if [ -x _build/lib/oqsprovider.0.5.0-dev.dylib ]; then
		echo "Successful build for Macports-installed OpenSSL"
        # Workaround for OpenSSL-3.1.0 bug
        sudo cp "${HOME}/src/openssl.block.cnf" "${OPENSSL_CONF}"
        echo "Uri's DYLD_LIBRARY_PATH=\"${DYLD_LIBRARY_PATH}\""
		scripts/runtests.sh 2>&1 | tee tests-out.txt
        # Restore correct OpenSSL config
        sudo cp "${HOME}/src/openssl.cnf" "${OPENSSL_CONF}"
		sudo cp _build/lib/oqsprovider.0.5.0-dev.dylib "$OPENSSL_MODULES"
	else
		echo "Apparently, building for Macports-installed OpenSSL-3 failed"
		echo ""
	fi	
else
	echo ""
	echo "Macports-installed OpenSSL-3 not found, skipping..."
	echo ""
fi

export DYLD_LIBRARY_PATH="${DYLD}"

date

exit 0
```

Result:
```text
Uri's DYLD_LIBRARY_PATH="/opt/local/lib:/usr/local/lib:"
Test setup:
LD_LIBRARY_PATH=/opt/local/lib:/usr/local/lib:
OPENSSL_APP=/opt/local/libexec/openssl3/bin/openssl
OPENSSL_CONF=/opt/local/libexec/openssl3/etc/openssl/openssl.cnf
OPENSSL_MODULES=/opt/local/libexec/openssl3/lib/ossl-modules
DYLD_LIBRARY_PATH=/opt/local/lib:/usr/local/lib:
No OQS-OpenSSL111 interop test because of absence of docker
Version information:
OpenSSL 3.1.1 30 May 2023 (Library: OpenSSL 3.1.1 30 May 2023)
Providers:
  base
    name: OpenSSL Base Provider
    version: 3.1.1
    status: active
    build info: 3.1.1
    gettable provider parameters:
      name: pointer to a UTF8 encoded string (arbitrary size)
      version: pointer to a UTF8 encoded string (arbitrary size)
      buildinfo: pointer to a UTF8 encoded string (arbitrary size)
      status: integer (arbitrary size)
  default
    name: OpenSSL Default Provider
    version: 3.1.1
    status: active
    build info: 3.1.1
    gettable provider parameters:
      name: pointer to a UTF8 encoded string (arbitrary size)
      version: pointer to a UTF8 encoded string (arbitrary size)
      buildinfo: pointer to a UTF8 encoded string (arbitrary size)
      status: integer (arbitrary size)
  legacy
    name: OpenSSL Legacy Provider
    version: 3.1.1
    status: active
    build info: 3.1.1
    gettable provider parameters:
      name: pointer to a UTF8 encoded string (arbitrary size)
      version: pointer to a UTF8 encoded string (arbitrary size)
      buildinfo: pointer to a UTF8 encoded string (arbitrary size)
      status: integer (arbitrary size)
  oqsprovider
    name: OpenSSL OQS Provider
    version: 0.5.0-dev
    status: active
    build info: OQS Provider v.0.5.0-dev (07107de) based on liboqs v.0.8.0-rc1
    gettable provider parameters:
      name: pointer to a UTF8 encoded string (arbitrary size)
      version: pointer to a UTF8 encoded string (arbitrary size)
      buildinfo: pointer to a UTF8 encoded string (arbitrary size)
      status: integer (arbitrary size)
  pkcs11
    name: PKCS#11 Provider
    version: 3.1.0
    status: active
    build info: 3.1.0
    gettable provider parameters:
      name: pointer to a UTF8 encoded string (arbitrary size)
      version: pointer to a UTF8 encoded string (arbitrary size)
      buildinfo: pointer to a UTF8 encoded string (arbitrary size)
      status: integer (arbitrary size)
Cert gen/verify, CMS sign/verify, CA tests for all enabled OQS signature algorithms commencing: 

Test project /Users/ur20980/src/oqs-provider/_build
    Start 1: oqs_signatures
1/5 Test #1: oqs_signatures ...................   Passed    2.19 sec
    Start 2: oqs_kems
2/5 Test #2: oqs_kems .........................   Passed    0.23 sec
    Start 3: oqs_groups
3/5 Test #3: oqs_groups .......................   Passed    0.33 sec
    Start 4: oqs_tlssig
4/5 Test #4: oqs_tlssig .......................   Passed    0.01 sec
    Start 5: oqs_endecode
5/5 Test #5: oqs_endecode .....................   Passed    4.54 sec

100% tests passed, 0 tests failed out of 5

Total Test time (real) =   7.30 sec

All oqsprovider tests passed.
```

**Comment by baentsch** [comment]
> you were talking about liboqs_DIR - that's the only potentially needed thing, and I can't find any of your scripts using this var.

That's a very correct observation. I only referenced it to let you know how to improve your local OSX script but didn't think about adding it as a feature to our cross-platform script. This oversight has now been fixed in https://github.com/open-quantum-safe/oqs-provider/commit/6d562bf066d575259f633fbea286bb46bb515054. I hope this helps/resolves your issue. If not, please consider contributing a PR working in your setup as well as our CI system and in https://github.com/openssl/openssl/blob/master/test/recipes/95-test_external_oqsprovider.t.

**Comment by mouse07410** [comment]
Looks like I'm not experiencing this bug anymore. Closing, at least until/unless this problem re-appears.
