### ISSUE TITLE
Question: Draft standards implemented by this provider.

### ISSUE THREAD

**Issue by fwh-dc** [open-quantum-safe/oqs-provider#189]
**Describe the bug**
Missing documentation of draft standards implemented by this provider.

**Additional context**
I'd like to know which draft standards are implemented as part of this provider. My understanding is besides the KEM's and SIG's [hybrid tls](https://datatracker.ietf.org/doc/draft-ietf-tls-hybrid-design/) is also part of the provider? Maybe you can clarify outstanding standardisation work done as part of this project?

Thanks,
Frederik

**Comment by baentsch** [comment]
Thanks for the feedback. You're right, this project needs more information in that area as it's "slowly" becoming independent from the old oqs-openssl111 code (and documentation) base. Any further questions (and/or direct contributions) to the documentation (and/or anything else of interest to you) are very welcome.
