### ISSUE TITLE
Implement KEM en-/decoders

### ISSUE THREAD

**Issue by Muzosh** [open-quantum-safe/oqs-provider#194]
In #123, PKCS#8 encoders for Dilithium, Falcon and Sphincs+ were added.
However, the initial message also links draft for Kyber. Why was it not included in the PR (I can't see any mention of Kyber in Files changed)?

In https://github.com/open-quantum-safe/oqs-provider/issues/84#issuecomment-1296125057, @baentsch mentions that KEM algorithms do not need to have encoder/decoder functions. What if I want to use openssl to generate Kyber1024 keypair? I didn't find a way to do it, even in raw form.

**Comment by baentsch** [comment]
The answer to the question is "Yes": Indeed there are no en-/decoders for Kyber (or any other PQ-KEM). The rationale was that we (thought we)'d need to persist key material only for PQ-signature algorithms (for X.509 etc)... Which `openssl` commands would/should benefit from persisting PQ-KEM key material (beyond key gen)?

**Comment by Muzosh** [comment]
Btw is there a way to do Kyber keygen, where openssl at least outputs keys in their raw form? Similar to what libOQS actually returns when keygen function executes? I know I can use any programming language and run libOQS from there, but I guess it would be nice to have in openssl as it is system-wide command-line application.

**Comment by baentsch** [comment]
@Muzosh Considering the above, do you still see a need for exporting KEM keys? Which standard(s) would you like to see this following then? If so, would you want to re-name this issue to "Implement KEM en-/decoders" (listing the standards this should implement)?

**Comment by Muzosh** [comment]
Sorry, I didn't find the time to get back to it. I will think about it.

**Comment by Muzosh** [comment]
@baentsch you mentioned CMS with KEM as an example. I'm actually working on a PQ version of something very similar: [CDOC](https://www.id.ee/en/article/bdoc-cdoc-and-asice-digidoc-file-formats-4/). In the reference implementation of [CDOC2](https://github.com/open-eid/cdoc2-java-ref-impl) (new version that I'm trying to make quantum-safe), they are currently using ECDH and RSA for creating Content Encryption Key for recipients. Therefore KEM encoders might come in handy to serialize Kyber and other PQ-KEM public keys in different key distribution systems.

I have other ways on how to generate and store Kyber keys myself for now, so there is no rush.

**Comment by baentsch** [comment]
Thanks for letting us know.

> KEM encoders might come in handy to serialize Kyber and other PQ-KEM public keys

Agreed.

**Comment by Muzosh** [comment]
> I have other ways on how to generate and store Kyber keys myself for now, so there is no rush.

Meaning that I can wait for more use cases from others, so it becomes more relevant and worth.

**Comment by ralienpp** [comment]
@baentsch, my colleagues and I are working on implementing the KEM features of [RFC4210bis](https://lamps-wg.github.io/cmp-updates/draft-ietf-lamps-rfc4210bis.html) in OpenSSL. We've made good progress and successfully tested everything with RSA-KEM, and we'd like to do it with post-quantum algorithms too. Our bottleneck is the lack of KEM encoders and decoders in the provider.

We'd like to test it with Kyber (because we already have an [implementation in Java](https://github.com/siemens/cmp-ra-component)), but eventually we'll want to test it with all post-quantum KEMs.

If you are looking for a good use case - I think this is it. The work done so far is in this [branch of OpenSSL](https://github.com/siemens/openssl/tree/add_KEM_support), we'll merge it into the upstream project as soon as everyone is happy with it (CC @rajeev-0).

**Comment by baentsch** [comment]
@ralienpp This indeed sounds like a good use case. Two immediate questions:
1) Can you provide a list of `openssl` commands you'd want to use/possibly already test this (RSA-KEM) with?
2) Is there a list of OIDs for (PQ)KEMs we could use (if I get you right you already have Kyber implemented in Java, so probably already use some... Can you point to the code or another location please)?

**Comment by ralienpp** [comment]
To the best of my knowledge, no OIDs are defined yet. In our experiments we use a dummy value of `1,2,3,4,1945,1111,9999` for Kyber512, with the intention to replace it as soon as the world moves on.

The logic can be triggered via openssl's `cmp` command. Here's a recipe you can follow to invoke the KEM-related logic from the aforementioned openssl branch. The test environment requires a CMP server and a CMP client, both can be simulated with OpenSSL. A scenario can look like this:

```
$cd openssl/test/recipes/80-test_cmp_http_data/Mock
# Run the server with a KEM key in one terminal 
$openssl cmp -config server_withkem.cnf -verbosity 8 -port 1700

# in another terminal, run the client
$openssl cmp -server 127.0.0.1:1700 -config test_withserverkem.cnf -section "Mock commands" -no_proxy 127.0.0.1 -cmd ir -cert signer.crt -key signer.key -srvcert kem.crt -certout out.test.pem 
```

The configuration files, certificates and keys used by the mock are a [part of the repository](https://github.com/siemens/openssl/tree/add_KEM_support/test/recipes/80-test_cmp_http_data/Mock), so the example should work out of the box.


To tinker with a post-quantum KEM, you'll need a KEM certificate. At the moment I have no elegant of producing one (normally I'd do it with OpenSSL :-). I'm attaching a sample I concocted manually, by taking a classic cert, replacing the subject public key with the raw bytes of Kyber512 as returned by liboqs/python and wrapped in a BitString, changing the algorithm OID; then signing it it with an RSA key and updating the signature. 

[kem-cert-experiment.zip](https://github.com/open-quantum-safe/oqs-provider/files/12421242/kem-cert-experiment.zip)

**Comment by Muzosh** [comment]
> Is there a list of OIDs for (PQ)KEMs we could use (if I get you right you already have Kyber implemented in Java, so probably already use some... Can you point to the code or another location please)?

I have found that BouncyCastle expanded on [OQS's OIDs](https://github.com/open-quantum-safe/oqs-provider/blob/main/ALGORITHMS.md) in their [BCObjectIdentifiers.java](https://github.com/bcgit/bc-java/blob/91c3c6018ab353f653749b9b56d6de384a31ec3c/core/src/main/java/org/bouncycastle/asn1/bc/BCObjectIdentifiers.java).

Process for finding this was really hard and frustrating, because documentation of PQ capabilities in BC is almost non-existent. But following their variables in this class, you can construct an KEM OID that they use for various PQ KEM algorithms.

**Comment by baentsch** [comment]
> To tinker with a post-quantum KEM, you'll need a KEM certificate. At the moment I have no elegant of producing one (normally I'd do it with OpenSSL :-)

Could you please provide `openssl` commands you'd use to do this? The only suitable command(s) I can think of are `genpkey` and `req -new`. The former works fine for the private key (also storing it with a suitably added encoder works OK), but the latter (intended to create and store the public key) doesn't quite work -- arguably because it (correctly) cannot use the (KEM!) algorithm to sign (the CSR).

So, beyond the CMP example above (beginning only when key & cert exists), can you please provide `openssl` commands you can use right now to create a classic crypto KEM certificate (without --internally-- triggering the use of a signature function for that algorithm)? Those would be the first commands I'd like to check correct function of the new KEM en/decoders with. If such `openssl` commands don't (yet) exist, I guess this use-case/issue will need to move "upstream".

**Comment by rajeev-0** [comment]
You could create the certificate without generating the CSR by using `openssl x509` with `-force_pubkey`. e.g.

`openssl x509 -new -subj "/CN=KEM_CERT" -CA <root.crt> -CAkey <root.key>  -out <kem.crt> -force_pubkey <kem_pub.pem>  -extensions SAN -extfile <(printf "[SAN]\nbasicConstraints=critical,CA:false\nkeyUsage=critical,keyEncipherment")`

**Comment by baentsch** [comment]
> You could create the certificate without generating the CSR by using `openssl x509` with `-force_pubkey`. e.g.
> 
> `openssl x509 -new -subj "/CN=KEM_CERT" -CA <root.crt> -CAkey <root.key> -out <kem.crt> -force_pubkey <kem_pub.pem> -extensions SAN -extfile <(printf "[SAN]\nbasicConstraints=critical,CA:false\nkeyUsage=critical,keyEncipherment")`

Well, this command uses a public key in a file (the "-force_pubkey" argument), but how is (a representation of) the public key stored in such file in the first place? According to https://github.com/openssl/openssl/discussions/22121#discussioncomment-7041853 no such command exists.

In other words, this issue cannot be resolved before https://github.com/openssl/openssl/issues/22132 is resolved.
