### ISSUE TITLE
Unfork repo

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-provider#197]
When doing a `homebrew` formula to auto-install `oqsprovider` in OSX, the following audit message came up making it impossible to submit the install formula as a PR for wider distribution:

```
> brew audit --new-formula  oqsprovider
oqsprovider
  * GitHub fork (not canonical repository)
Error: 1 problem in 1 formula detected.
```

So I'd think the time has come to detach ("unfork") the project from the initial setup by @levitte.

At the time, forking seemed reasonable, a) to recognize the work extracting our code from [oqs-openssl](https://github.com/open-quantum-safe/openssl/tree/OQS-OpenSSL3) and b) because it wasn't entirely clear we'd carry on the project separately from ´oqs-openssl´.

This changed by now: a) We'll document code (and work) heritage by updates to the README (as part of #195) and b) definitely carry this work forward independently of `oqs-openssl` (actually end support for that project in favour of `oqsprovider`).

Is this OK, particularly for you, @levitte? Any objections, @dstebila @bhess ?

**Comment by levitte** [comment]
I'm perfectly ok with that.  Ping me when done, and I'll remove my repo (which was meant to be exactly what it became, a kick-starter)...

**Comment by baentsch** [comment]
> Ping me when done

Ping: https://support.github.com/ticket/personal/0/2225768

And Thanks again for the kick (-starter :-)

**Comment by levitte** [comment]
Cool.  levitte/tmp-oqsprov is now gone.
