### ISSUE TITLE
issue while ruuning $openssl list -providers

### ISSUE THREAD

**Issue by MeherP2246** [open-quantum-safe/oqs-provider#206]
i have added the below lines in my /etc/ssl/openssl.cnf file.

[provider_sect]
default = default_sect
oqsprovider = oqsprovider_sect
[oqsprovider_sect]
activate = 1

but after running the $ openssl list -providers command it was only showing the below as an output , which meas my oqs-provider is not activate yet? 

openssl list -providers

Providers:
  default
    name: OpenSSL Default Provider
    version: 3.2.0
    status: active

please help me to solve this one

**Comment by baentsch** [comment]
Most likely `openssl` cannot find `oqsprovider.so`: Please be sure to have worked through [the setup documentation regarding module deployment](https://github.com/open-quantum-safe/oqs-provider/blob/main/USAGE.md#module-option).

**Comment by baentsch** [comment]
@MeherP2246 Any news? Did you try setting `module` or `OPENSSL_MODULES`? Can we close the issue?
