### ISSUE TITLE
openssl s_client seems to work but s_time does not

### ISSUE THREAD

**Issue by cryptobsv** [open-quantum-safe/oqs-provider#223]
openssl s_client seems to work but s_time does not

I create a self-signed cert:
`openssl req -x509 -new -newkey dilithium2 -keyout CA.key -out CA.crt -nodes -subj "/CN=oqstest CA" -days 365`
I start a server:
`openssl s_server -cert CA.crt -key CA.key -curves kyber512 -www -tls1_3 -accept 127.0.0.1:8080 &`
I connect with
`openssl s_client -connect 127.0.0.1:8080`
and I see it connects.
If I try to connect with
`openssl s_time -connect 127.0.0.1:8080`
I get an error
```
Collecting connection statistics for 30 seconds
ERROR
20E05889FFFF0000:error:0A000065:SSL routines:final_key_share:no suitable key share:
../git/ssl/statem/extensions.c:1470:
20305190FFFF0000:error:0A000410:SSL routines:ssl3_read_bytes:ssl/tls alert handshak
e failure:../git/ssl/record/rec_layer_s3.c:856:SSL alert number 40
```
I'm using openssl 3.2.0-dev (commit 709ef409) on an ARM platform and oqsprovider 0.5.1-dev (commit 0c91d091).
Is there anything I am obviously doing wrong? Thanks!

**Comment by baentsch** [comment]
> Is there anything I am obviously doing wrong? Thanks!

Yes: The server specs "kyber512" as KEM group while the client does not. So it will use whatever default group you have spec'd (most likely X25519): Mayhem ensues.

FWIW, here's what we do in [profiling](https://github.com/open-quantum-safe/profiling) for https://openquantumsafe.org/benchmarking: https://github.com/open-quantum-safe/profiling/blob/246d36484c8529d46a9c3f94a713f2d2a37f3a78/perf/Dockerfile#L65C1-L65C510 or more readable in [the usage documentation](https://github.com/open-quantum-safe/oqs-provider/blob/main/USAGE.md#configuration-parameter) to work around this `openssl` limitation (of not being able to spec the TLS1.3 group on the command line for `s_time`).

**Comment by cryptobsv** [comment]
Thanks for the quick reply. For the benefit of anyone with the same problem, I'll quickly summarize how I got `openssl s_time` to work.
Modifying openssl.cnf as in https://github.com/open-quantum-safe/oqs-provider/blob/main/USAGE.md#configuration-parameter did the trick.
(Before that, I tried setting the environment variable DEFAULT_GROUPS (as in https://github.com/open-quantum-safe/profiling/blob/246d36484c8529d46a9c3f94a713f2d2a37f3a78/perf/scripts/handshakes.py#L51C6-L51C6), but that did not work.)

**Comment by baentsch** [comment]
>  I tried setting the environment variable DEFAULT_GROUPS (as in https://github.com/open-quantum-safe/profiling/blob/246d36484c8529d46a9c3f94a713f2d2a37f3a78/perf/scripts/handshakes.py#L51C6-L51C6), but that did not work.

No, that (alone) could not have worked as it depends on 

> [system_default_sect]
Groups = $ENV::DEFAULT_GROUPS

being present in "openssl.cnf" (as per the above-mentioned "straightforward `sed`" statements: https://github.com/open-quantum-safe/profiling/blob/246d36484c8529d46a9c3f94a713f2d2a37f3a78/perf/Dockerfile#L65C1-L65C510 :-)
