### ISSUE TITLE
Format source code with ClangFormat.

### ISSUE THREAD

**Issue by thb-sb** [open-quantum-safe/oqs-provider#224]
Hello,

I'm wondering if this project could use [ClangFormat] to format the source code (both non-generated and generated).
It may be useful to achieve consistency in the code format.

What do authors think about it?

[ClangFormat]: https://clang.llvm.org/docs/ClangFormat.html

**Comment by baentsch** [comment]
It would certainly make code more consistent(ly readable). So IMO it'd be a good enhancement. When setting the style, my preference would be the [OpenSSL coding style](https://www.openssl.org/policies/technical/coding-style.html).
