### ISSUE TITLE
Loading oqsprovider fails via API load under Windows

### ISSUE THREAD

**Issue by VeronikaNguyen** [open-quantum-safe/oqs-provider#237]
I am trying to load the oqsprovider via code under Windows since loading the provider over the openssl config is not an option for me. 
The `oqsprovider.dll` file is located in `D:\projects\certificate_scripts`. When running the following commands
```  
OSSL_PROVIDER_set_default_search_path(NULL, "D:\\projects\\certificate_scripts");
auto path = OSSL_PROVIDER_get0_default_search_path(NULL);
auto loaded = OSSL_PROVIDER_load(NULL, "oqsprovider");
```
`path` is set correctly, however, `loaded` is `NULL`, which indicates that the provider was not successfully loaded.

When printing out the error with 
```
  int err = ERR_get_error();
  char buf[256];
  ERR_error_string_n(err, buf, sizeof(buf));
```
it says `error:078C0105:common libcrypto routines::init fail`.

Am I missing something here? I am grateful for every kind of input.

**Comment by baentsch** [comment]
I only have very little experience with Windows, sorry. Also the error message seems to be pretty generic/not really OQS-related: Are you certain to have set up all other code correctly? For example, can you load the "default" provider via the code above OK?

**Comment by VeronikaNguyen** [comment]
Thank you for the quick answer! Yes, I am quite certain that the other code is set up correctly. Loading the "default" provider via the above code works. 

I will ask the same question in the openssl forum.

**Comment by VeronikaNguyen** [comment]
> Have you loaded the default provider and then tried to load oqsprovider?

Yes, however, this still does not work.

I used the `oqsprovider.dll` attached to release version 0.5.1. Loading the provider works if I set the environment variable `OPENSSL_CONF` and activate the `oqsprovider`.

**Comment by baentsch** [comment]
> Loading the provider works if I set the environment variable OPENSSL_CONF and activate the oqsprovider.

Ahh -- that is interesting. Then the "machinations of OQS (initialization)" don't play a role, but it's indeed a question how things have to be set up via the OpenSSL APIs: Please post a link to the discussion in OpenSSL -- I'd be curious to learn what comes up there.

Final question from my side: Have you tried running your C code in Unix/Linux to see whether this is a Windows-only issue? I'd be happy to try your code if you don't have such environment.

**Comment by marcbrevoort-cyberhive** [comment]
You might need to load the config in code with CONF_modules_load_file.

**Comment by baentsch** [comment]
> You might need to load a pq-activated config in code with `CONF_modules_load_file`.

Definitely worth while trying. This shouldn't change things materially as provider activation happens implicitly when calling `OSSL_PROVIDER_load`, but why not checking this out?

**Comment by VeronikaNguyen** [comment]
@marcbrevoort-cyberhive Thanks for the suggestion. I tried it out but it didn't change the result.

@baentsch It would be great if you could try this out under Linux for me.

```
#include <openssl/conf.h>
#include <openssl/provider.h>

int main()
{
    auto libctx = OSSL_LIB_CTX_new();
    //OSSL_LIB_CTX_load_config(libctx, "D:\\projects\\openssl.cfg");
    //CONF_modules_load_file("D:\\projects\\openssl.cfg", NULL, NULL);
    OSSL_PROVIDER_set_default_search_path(libctx, "D:\\projects\\certificate_scripts");     // path is set to location of oqsprovider.dll
    OSSL_PROVIDER_load(libctx, "default");
    OSSL_PROVIDER_load(libctx, "oqsprovider");
}
```

**Comment by baentsch** [comment]
This works like a charm under Linux:

```
$ cat test.c
#include <openssl/conf.h>
#include <openssl/provider.h>

int main()
{
    OSSL_LIB_CTX* libctx = OSSL_LIB_CTX_new();
    OSSL_PROVIDER_set_default_search_path(libctx, "_build/lib");     // path is set to location of oqsprovider.dll
    printf("load default result: %p\n", OSSL_PROVIDER_load(libctx, "default"));
    printf("load oqsprovider result: %p\n", OSSL_PROVIDER_load(libctx, "oqsprovider"));
}


$ gcc test.c -lcrypto
$ ./a.out 
load default result: 0x55fa28183d50
load oqsprovider result: 0x55fa281846b0

```

**Comment by baentsch** [comment]
PS: Any change (wrong path, wrong provider name, etc) lead to an expected "(nil)" output in the second line.

**Comment by VeronikaNguyen** [comment]
@baentsch Thanks for trying this out for me under Linux. It's good to know that this might be a Windows error. 

>PS: Any change (wrong path, wrong provider name, etc) lead to an expected "(nil)" output in the second line.

Checked for the path and name multiple times.

**Comment by baentsch** [comment]
I'm afraid then there's no way around asking for help from the (Windows) OpenSSL community. Please post a link here when you have opened an [issue](https://github.com/openssl/openssl/issues) (or reference this issue) so we can learn the resolution as and when available.

**Comment by VeronikaNguyen** [comment]
https://github.com/openssl/openssl/discussions/21903

**Comment by VeronikaNguyen** [comment]
Thank you very much @baentsch for the quick fixing of the issue.

**Comment by baentsch** [comment]
> Thank you very much @baentsch for the quick fixing of the issue.

You're welcome. Thanks in turn for raising it and helping getting to the cause of this. Made the software a bit better... I hope -- could you confirm your issue is truly resolved?

**Comment by VeronikaNguyen** [comment]
Not yet, but I will try out soon.
