### ISSUE TITLE
cmake Issues building with an existing OpenSSL build: liboqs_DiR ?

### ISSUE THREAD

**Issue by planetf1** [open-quantum-safe/oqs-provider#265]
**Describe the bug**
cmake Issues building with an existing OpenSSL build

**To Reproduce**
I am trying to build openssl, liboqs & oqs-provider from scratch.
Fedora 39. Both clang and gcc installed
Configuring in visual studio code using make, cmake, c/c++ plugins

source is under /home/jonesn/src

1. Build openSSL
* `./Configure --prefix=/home/jonesn/opt/openssl --openssldir=/home/jonesn/usr/local/ssl `
* `make`
* Observe: libssl.a & libcrypto.a are in the top level source directory (no specific build output directory), whilst shared library versions such as libcrypto.so & libssl.so are in /home/jonesn/opt/ssl/lib

2. Build liboqs
* Configure cmake with `-DCMAKE_BUILD_TYPE=Debug -DOPENSSL_ROOT_DIR=/home/jonesn/opt/openssl -DCMAKE_INSTALL_PREFIX=/home/jonesn/usr/local`
* build with cmake
* Observe: output file is build/lib/liboqs.a - this is the default build target 

3. Attempt to build provider
* Use same cmake options as in step 2
* Also set `-D-Dliboqs_DIR=/home/jonesn/src/liboqs/build`

Configuration fails 
```
[proc] Executing command: /usr/bin/cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/jonesn/usr/local -DOPENSSL_ROOT_DIR=/home/jonesn/opt/openssl -Dliboqs_DIR=/home/jonesn/src/liboqs/build/src -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++ -S/home/jonesn/src/oqs-provider -B/home/jonesn/src/oqs-provider/_build -G "Unix Makefiles"
....
[cmake] CMake Error at /home/jonesn/src/liboqs/build/src/liboqsConfig.cmake:29 (include):
[cmake]   include could not find requested file:
[cmake] 
[cmake]     /home/jonesn/src/liboqs/build/src/liboqsTargets.cmake
```
This file is actually in `./liboqs/build/src/cmake/liboqsTargets.cmake` ie the cmake subdirectory

the source line from liboqs is 
```
include("${CMAKE_CURRENT_LIST_DIR}/liboqsTargets.cmake")
```
so I presume something isn't quite right with the context in which this is run

**Expected behavior**
Ability to build liboqs, openssl, oqs_provider all from source

**Screenshots**
none

**Environment (please complete the following information):**
 - OS: Fedora 39
 - OpenSSL version: 3.2.0-alpha2-dev
 - oqsprovider version: main (HEAD @ 6d1ce1862b83cf73bcf410132a2c0699e962177b )

Please run the following commands to obtain the version information:
 - For OpenSSL: `openssl version` -> see above
 - For oqsprovider: `openssl list -providers` -> not build

**Additional context**
The build instructions are not used verbatim - but the configuration documents & steps for configuring and building for each product have been used- I am trying to get the build working within vscode to provide myself with a smoother dev environment & share with colleagues - and community if useful. 

**Hints**

**Comment by baentsch** [comment]
Several observations:

1) Did you run `cmake --install` for `liboqs` or only build? That would explain why the lib is not winding up in the spec'd "CMAKE_INSTALL_PREFIX"

2) Is '-D-Dliboqs_DIR=/home/jonesn/src/liboqs/build' a typo? Double "-D" will cause problems. Also, please try setting this not just as a `cmake` define but also as an environment variable, i.e., as such "export liboqs_DIR=/home/jonesn/src/liboqs/build" (or whatever install prefix you want for `liboqs`). The way `cmake` honours this is a bit beyond my understanding -- and Fedora/RHEL seem to be particularly "picky". Tagging your colleagues @bhess @beldmit for assistance with this environment.

**Comment by planetf1** [comment]
@thb-sb The issue with the cmake files from liboqs are :

➜  liboqs git:(main) find . -name liboqsConfig.cmake                                                                                        git:(main|) 
./build/src/liboqsConfig.cmake
➜  liboqs git:(main) find . -name liboqsTargets.cmake                                                                                       git:(main|) 
./build/src/CMakeFiles/Export/8aa5f49adc8abed80015a916ce81e944/liboqsTargets.cmake
./build/src/cmake/liboqsTargets.cmake
➜  liboqs git:(main)                

ie they are in different directories.

I did NOT run the cmake --install -- just the default target for liboqs - I know there was going to be a move away from ninja, though the docs still refer to it. No ninja config files though.. I'll persue this 'install' angle

@baentsch 
1. as above - will persue
2. That was my error pasting into github ;-) command is fine

cmake is new to me too.

Thanks for the tips - I'll look into the install angle  for liboqs and persue where these files should be

**Comment by baentsch** [comment]
> ie they are in different directories.

Those are all build directories -- they are not what is/needs to be installed.

> I'll look into the install angle for liboqs and persue where these files should be

That should resolve most (ideally all :) issues.

**Comment by planetf1** [comment]
Thanks,
 The missing step was the 'install'.
 
 After running this on liboqs
 * cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/jonesn/usr/local -DOPENSSL_ROOT_DIR=/home/jonesn/opt/openssl
 * ninja install
 
 And then setting
 -Dliboqs_DIR=/home/jonesn/src/usr/local
 
 the provider then builds.
 
 I'm thinking maybe a little clarification could be added to the docs, to clarify the openssl library needs to be installed, probably in CONFIGURE.md. I can raise a small PR on this. (I had usr & include in source so met the criteria currently listed)
 
 Thanks for the help!

**Comment by baentsch** [comment]
> I'm thinking maybe a little clarification could be added to the docs, to clarify the liboqs library needs to be installed,

Maybe not: This is just two references to already existing docs:

https://github.com/open-quantum-safe/oqs-provider/blob/main/NOTES-UNIX.md#liboqs

https://github.com/open-quantum-safe/oqs-provider/blob/main/CONFIGURE.md#liboqs_dir :

> This environment variable must be set to the location of the liboqs installation

In addition, when using the "fullbuild.sh" script everything is taken care of.
