### ISSUE TITLE
Remove default algs, BIKEr2; add BIKEr3

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-provider#27]
Pursuant https://github.com/open-quantum-safe/openssl/pull/313 

@bhess: When doing this (assumed simple) update I had to notice that the new NIDs you created "extra" now clash with those we had to make up in oqs-openssl to keep "s2n history"... Please check out #26 for a first cut at resolving this issue: Would you want to make a suggestion how to fix things now? Either "registering" your new hybrid NIDs via an amend-commit to https://github.com/open-quantum-safe/openssl/pull/313 or amend #26 (change extra-NIDs) here. I'd prefer the latter (updating extra NIDs) to not make things more complicated in oqs-openssl.

**Comment by bhess** [comment]
I'm ok with the latter option as well, updating the extra NIDs in #26. 

Looking at https://github.com/open-quantum-safe/openssl/pull/313, what changes are some 3rd round code points (which can be updated by running generate.py, BIKEr3 with ecx hybrids (which is new for oqs-provider), and the Kyber ecx hybrids (which is now conflicting with oqs-provider). For Kyber-ecx it's ok with me to just update the code point here.

**Comment by baentsch** [comment]
OK, shall I then simply chose different NIDs in `generate-extras.yml` or would you want to propose a change to those as a commit-update to this PR?

**Comment by bhess** [comment]
> OK, shall I then simply chose different NIDs in `generate-extras.yml`

Thanks, yes that would be fine for my side.
