### ISSUE TITLE
Falcon and SPHINCS+ interop with BC

### ISSUE THREAD

**Issue by praveksharma** [open-quantum-safe/oqs-provider#270]
**Describe the bug**
The current SPHINCS+ implementation doesn't interop with Bouncy Castle under the [R3 format](https://github.com/IETF-Hackathon/pqc-certificates/tree/master#zip-format-r3) used the PQC Certificates project of IETF hackathons. oqs-provider is unable to verify self-signed certificates produced by Bouncy Castle. This occurs despite the OIDs in [Bouncy Castle](https://github.com/bcgit/bc-java/blob/e007cbe82622e2f3d2ba0c46cceab7d504d4cf9b/core/src/main/java/org/bouncycastle/asn1/bc/BCObjectIdentifiers.java#L157C3-L157C3) matching those in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider/blob/fab30c7f4bb40898aab2a967cdd6b0f990091778/oqs-template/generate.yml#L735).

**To Reproduce**
```
git clone https://github.com/IETF-Hackathon/pqc-certificates.git
# Extract provider/bc/artifacts_certs_r3.zip to providers/bc/artifacts/
cd providers/bc/
../oqs/check_r3.sh .
```

**Expected behavior**
The script should output `Y` for each certificate signed using SPHINCS+:

```
1.3.9999.6.4.13,Y
1.3.9999.6.4.16,Y
1.3.9999.6.5.10,Y
1.3.9999.6.5.12,Y
1.3.9999.6.6.10,Y
1.3.9999.6.6.12,Y
1.3.9999.6.7.13,Y
1.3.9999.6.7.16,Y
1.3.9999.6.8.10,Y
1.3.9999.6.8.12,Y
1.3.9999.6.9.10,Y
1.3.9999.6.9.12,Y
```

**Environment:**
Docker container based on image built with [`/opensll3/Dockerfile-interop`](https://github.com/open-quantum-safe/oqs-demos/blob/main/openssl3/Dockerfile-interop) from oqs-demos. The Dockerfile was modified to build oqs-provider from the interop-test branch instead of main.

- OpenSSL: 3.2.0-alpha3-dev
- oqsprovider: 0.5.2-interop

**Comment by praveksharma** [comment]
The information in this issue differs from my report in the status meeting on 03 October 2023. I hadn't realised at the time of running of running interop tests that the updated OIDs had been merged into the interop-test branch of oqs-provider and not the main branch. The information I present here is the result of re-running the tests using the correct branch of oqs-provider. @baentsch @dstebila @SWilson4 

Here's a summary of other tests which are failing at the moment:
- BC: falcon (incorrect OIDs in BC)
- botan: dilithium (incorrect OIDs in botan)
- carl-redhound: dilithium and falcon (incorrect OIDs in carl-redhound)
- corey-digicert: dilithium (incorrect OIDs in corey-digicert)
- cryptonext: dilithium and falcon (incorrect OIDs in cryptonext)
- entrust: dilithium (incorrect OIDs in entrust)
- kris: dilithium and falcon (incorrect OIDs in kris)
- openca: dilithium and falcon (incorrect OIDs in openca)
- oqs-gnutls: dilithium (incorrect OIDs in oqs-gnutls)

**Comment by baentsch** [comment]
> The information in this issue differs from my report in the status meeting on 03 October 2023. 

Does this mean that "interop-test branch confirms OK interop between BC and OQS for Dilithium and Falcon but not for Sphincs+?

To make this more precise, can you please further provide the output of the command `openssl list -verbose -providers -provider oqsprovider` to document the complete software stack, most notably the `liboqs` version used in testing? I'm most concerned about the age of the Dockerfile used when building the test platform: 

> Docker container based on image built with [/opensll3/Dockerfile-interop](https://github.com/open-quantum-safe/oqs-demos/blob/main/openssl3/Dockerfile-interop) from oqs-demos. The Dockerfile was modified to build oqs-provider from the interop-test branch instead of main.

If https://github.com/open-quantum-safe/oqs-demos/blob/365196ae7417408b7bdf64eebbf3143e30266e39/openssl3/Dockerfile-interop#L57 did not also get modified to run "standard" branch, we'd not be testing what we expect...

> BC: falcon (incorrect OIDs in BC)

Does this mean you have confirmed the Falcon OIDs used in the hackathon and those used by OQS are the same but those that BC uses are _not_ the same? Or stated differently, Falcon and Sphincs+ interop between Botan and OQS is confirmed?

If you can confirm this, that'd be good news for OQS (less work :) and the PQCrystals teams: BC interop then would confirm that their "FIPS spec understanding" and the PQCrystals teams' _understanding_ of the spec are the same -- assuming BC has a separate code (for the "standard" Dilithium implementation) base and OQS(provider) has been running the (`liboqs`)"standard" branch. All other implementations having different OIDs would be expected if they do not yet implement the FIPS variant of Dilithium. If you feel like confirming this, please run a "main" branch build of `oqsprovider` and `liboqs` (built with "-DNOPUBKEY_IN_PRIVKEY=ON") against those implementations (i.e., an unchanged Dockerfile image from the previous IETF interop event): OK interop between OQS and Entrust etc (not implementing FIPS Dilithium) would be expected then.

**Comment by praveksharma** [comment]
> Does this mean that "interop-test branch confirms OK interop between BC and OQS for Dilithium and Falcon but not for Sphincs+?

No, the interop-test branch confirm OK interop between BC and OQS for Dilithium but not for Falcon (see below) and SPHINCS+.

> To make this more precise, can you please further provide the output of the command `openssl list -verbose -providers -provider oqsprovider` to document the complete software stack, most notably the `liboqs` version used in testing? I'm most concerned about the age of the Dockerfile used when building the test platform:
> If https://github.com/open-quantum-safe/oqs-demos/blob/365196ae7417408b7bdf64eebbf3143e30266e39/openssl3/Dockerfile-interop#L57 did not also get modified to run "standard" branch, we'd not be testing what we expect...

That line was indeed updated, here's the output `openssl list -verbose -providers -provider oqsprovider`:
```
Providers:
  default
    name: OpenSSL Default Provider
    version: 3.2.0
    status: active
    build info: 3.2.0-alpha3-dev
    gettable provider parameters:
      name: pointer to a UTF8 encoded string (arbitrary size)
      version: pointer to a UTF8 encoded string (arbitrary size)
      buildinfo: pointer to a UTF8 encoded string (arbitrary size)
      status: integer (arbitrary size)
  oqsprovider
    name: OpenSSL OQS Provider
    version: 0.5.2-interop
    status: active
    build info: OQS Provider v.0.5.2-interop (ed6462a) based on liboqs v.0.9.0-standard
    gettable provider parameters:
      name: pointer to a UTF8 encoded string (arbitrary size)
      version: pointer to a UTF8 encoded string (arbitrary size)
      buildinfo: pointer to a UTF8 encoded string (arbitrary size)
      status: integer (arbitrary size)
```
> Does this mean you have confirmed the Falcon OIDs used in the hackathon and those used by OQS are the same but those that BC uses are _not_ the same? 

Yes, I did confirm this, as seen in the [BC repos](https://github.com/bcgit/bc-java/blob/e007cbe82622e2f3d2ba0c46cceab7d504d4cf9b/core/src/main/java/org/bouncycastle/asn1/bc/BCObjectIdentifiers.java#L246) and by running [`/providers/bc/gen.sh`](https://github.com/IETF-Hackathon/pqc-certificates/blob/master/providers/bc/gen.sh) in the pqc-certificates repo.

> Or stated differently, Falcon and Sphincs+ interop between Botan and OQS is confirmed?

No, it is not confirmed. The pqc-certificates repo doesn't provide artifacts these algorithms as seen in [`providers/botan/`](https://github.com/IETF-Hackathon/pqc-certificates/tree/master/providers/botan). Further, while I'm not sure which version of Botan was used to produce the interop artifacts but the [master branch](https://github.com/randombit/botan/blob/5ccf554190949add414721e3652a8da66f67e520/src/lib/asn1/oid_maps.cpp) does not provide OIDs for Falcon and those for Sphincs+ are incorrect.

> If you feel like confirming this, please run a "main" branch build of `oqsprovider` and `liboqs` (built with "-DNOPUBKEY_IN_PRIVKEY=ON") against those implementations (i.e., an unchanged Dockerfile image from the previous IETF interop event): OK interop between OQS and Entrust etc (not implementing FIPS Dilithium) would be expected then.

I ran the tests with the unchanged Dockerfile image and the results match what you say.

**Comment by baentsch** [comment]
Thanks for these explanations and additional tests! So this issue should read "Falcon and Sphincs+ interop with BC" then? 

> No, the interop-test branch confirm OK interop between BC and OQS for Dilithium but not for Falcon (see below) and SPHINCS+.

> I ran the tests with the unchanged Dockerfile image and the results match what you say.

So is this summary correct then: (FIPS) Dilithium interop is confirmed (with BC as the only other implementation doing FIPS Dilithium using "interop-test" branch) and (Round3) Dilithium interop is confirmed with all other implementations (using "main branch")? Please note such confirmation would be running counter to the results stated in the [interop results table](https://github.com/IETF-Hackathon/pqc-certificates/blob/master/docs/pqc_hackathon_results_certs_r3.md#ml-dsa-44-ipd-13614122671244) for the "FIPS Dilithium" OID.

In general, your statement seems to indicate that all logic in oqs-provider (incl. (O)IDs) is correct (as there is no Dilithium-unique code in `oqsprovider` apart from labelling an algorithm via OID). Would you concur?

Addressing the core issue at stake here then, allow me to state some amount of skepticism towards the interop results presentation: Just looking at [Dilithium results](https://github.com/IETF-Hackathon/pqc-certificates/blob/master/docs/pqc_hackathon_results_certs_r3.md#dilithium2-1361412267744)
- there is no result mark between BC and oqsprovider (but between oqsprovider and BC): Why? Is the summary above _really_ correct then?
- OK interop is documented between Entrust and oqsprovider but not between oqsprovider and Entrust (the other direction): That might be understandable if oqsprovider had an error in either encoding or decoding logic -- but then it would fail with all other implementations in that direction too -- and that is not the case.

Digging to the next level: OQS seems to interoperate with Digicert and Entrust on [Falcon1024](https://github.com/IETF-Hackathon/pqc-certificates/blob/master/docs/pqc_hackathon_results_certs_r3.md#falcon-1024-13999939) -- but only in one direction: Why?

I have more and more confidence in the logic in `oqsprovider` looking at this -- I have not as much trust in hackathon results presentation and algorithm version identification in the different implementations (incl. OQS):

Worked example regarding Sphincs: Looking at [this interop results entry](https://github.com/IETF-Hackathon/pqc-certificates/blob/master/docs/pqc_hackathon_results_certs_r3.md#slh-dsa-sha2-128f-ipd-1399996413) the OID for this algorithm labelled "SLH-DSA-SHA2-128f-ipd" is identical to our OID for [SPHINCS+-SHA2-128f-simple](https://github.com/open-quantum-safe/oqs-provider/blob/ed6462a597c412ddd49297a00193d069a382c93d/oqs-template/generate.yml#L805-L808) --> With such OID clash interop is impossible (or is the above moniker indeed representing the same algorithm?). If not, you may want to re-do Sphincs tests with any OID adopted by the hackathon team: Any value can simply be set via [environment variable](https://github.com/open-quantum-safe/oqs-provider/blob/interop-test/ALGORITHMS.md#oids).

One more issue with the Sphincs interop results: [Here is a Sphincs interop results table](https://github.com/IETF-Hackathon/pqc-certificates/blob/master/docs/pqc_hackathon_results_certs_r3.md#sphincs-sha256-192f-simple-139999653): Looking at it, one may believe oqsprovider and entrust interoperate. However, this is impossible, as the stated OID is not active in oqsprovider any more (in "interop-test" branch). It used to be active in "main" branch. --> Is this results presentation an "amalgamation" of various previous runs? It would be sensible to add the output of `openssl list -verbose -providers -provider oqsprovider` (and the equivalent code identification methods in the other implementations) to all results to avoid such issues.

Final suggestion: Would it be sensible to drop `oqs-openssl111` from the results tables in the hackathon? This code is surely not run any more and accordingly, no results will ever be added again. The results presentation would become more legible, too.

**Comment by praveksharma** [comment]
I shall first attempt to address your concerns regarding the hackathon test result presentation. The test results are generated using a three step process:

1. Each provider generates artifacts in the [R3 format](https://github.com/IETF-Hackathon/pqc-certificates/blob/master/readme.md#zip-format-r3) and saves them as `providers/*/artifacts_certs_r3.zip`.
2. Each provider then checks for compatibility with all other providers and generates a compatibility matrix consisting of CSV files in `providers/*/compatMatrices/artifacts_certs_r3.zip`. Since these CSV files are generated manually, a provider may choose to not generate compatibility matrices for all other providers resulting in possible asymmetry in the final results as you note (looks like Digicert and Entrust did not generate the CSV files required to generate the compatibility matrix with oqs-provider):  
> OK interop is documented between Entrust and oqsprovider but not between oqsprovider and Entrust

>Digging to the next level: OQS seems to interoperate with Digicert and Entrust on [Falcon1024](https://github.com/IETF-Hackathon/pqc-certificates/blob/master/docs/pqc_hackathon_results_certs_r3.md#falcon-1024-13999939) -- but only in one direction
3. Once all the CSV files are generated (or changed), scripts inside `src/` must be manually run to update the final results. Since these scripts haven't been run the results you're seeing are out of date compared to the updated CSVs resulting in the inconsistencies you note:
> there is no result mark between BC and oqsprovider (but between oqsprovider and BC)

(the results are based on the CSVs generated by OQS Provider v.0.5.2-main which doesn't provide the required OID)
> One more issue with the Sphincs interop results: [Here is a Sphincs interop results table](https://github.com/IETF-Hackathon/pqc-certificates/blob/master/docs/pqc_hackathon_results_certs_r3.md#sphincs-sha256-192f-simple-139999653): Looking at it, one may believe oqsprovider and entrust interoperate. However, this is impossible, as the stated OID is not active in oqsprovider any more (in "interop-test" branch)

So the results are as you say:
>  Is this results presentation an "amalgamation" of various previous runs? It would be sensible to add the output of `openssl list -verbose -providers -provider oqsprovider` (and the equivalent code identification methods in the other implementations) to all results to avoid such issues.

I agree with adding the output of `openssl list -verbose -providers -provider oqsprovider`. I shall either open an issue on the pqc-certificates repo asking that the results be updated or attempt to update them myself. In the mean time, I suggest you refer to `/providers/oqs/compatMatrices/artifacts_certs_r3/*.csv` instead.

> So this issue should read "Falcon and Sphincs+ interop with BC" then?

I didn't think including the Falcon in the issue was necessary since it's the OIDs in BC which are out of date but I've updated the issue.

> So is this summary correct then: (FIPS) Dilithium interop is confirmed (with BC as the only other implementation doing FIPS Dilithium using "interop-test" branch) and (Round3) Dilithium interop is confirmed with all other implementations (using "main branch")? Please note such confirmation would be running counter to the results stated in the [interop results table](https://github.com/IETF-Hackathon/pqc-certificates/blob/master/docs/pqc_hackathon_results_certs_r3.md#ml-dsa-44-ipd-13614122671244) for the "FIPS Dilithium" OID.

Yes, I agree with this summary. Any inconsistency with the hackathon results are due to reasons I've listed above.

> In general, your statement seems to indicate that all logic in oqs-provider (incl. (O)IDs) is correct (as there is no Dilithium-unique code in `oqsprovider` apart from labelling an algorithm via OID). Would you concur?

Yes, I agree.

> With such OID clash interop is impossible (or is the above moniker indeed representing the same algorithm?). 

Yes, they are the same algorithm, NIST chose to name Sphincs+ SLH-DSA in FIPS 205 initial public draft.

> Final suggestion: Would it be sensible to drop `oqs-openssl111` from the results tables in the hackathon? This code is surely not run any more and accordingly, no results will ever be added again. The results presentation would become more legible, too.

I agree with you and removed `oqs-openssl111` results from `/providers/oqs/compatMatrices/artifacts_certs_r3/` when I last updated the CSVs. 

With these issues out of the way:

> Looking at it, one may believe oqsprovider and entrust interoperate. However, this is impossible, as the stated OID is not active in oqsprovider any more (in "interop-test" branch). 

While what you say is correct (as verified by the output of `openssl list -objects`) the up to date results in  `/providers/oqs/compatMatrices/artifacts_certs_r3/` (generated with OQS Provider v.0.5.2-interop (ed6462a) based on liboqs v.0.9.0-standard) show that Entrust (with incorrect OIDs) interops fine with oqs-provider while BC (with correct OIDs) does not interop with oqs-provider.

**Comment by baentsch** [comment]
> I suggest you refer to /providers/oqs/compatMatrices/artifacts_certs_r3/*.csv instead.

Thanks for that suggestion: Will do so (but would recommend the hackathon team to update the .md files too, just in case someone else reads/relies on them).

> since it's the OIDs in BC which are out of date 

If we know BC uses wrong OIDs then it's indeed not an issue for us to look at.

> show that Entrust (with incorrect OIDs) interops fine with oqs-provider while BC (with correct OIDs) does not interop with oqs-provider.

Nice summary. Are we 100% sure that BC uses the same Sphincs+ spec version as entrust and OQS do, then?

All in all, I don't see any concrete bug to fix in oqsprovider. Apologies for having suggested to create an issue -- it did help me to understand where we're at wrt interop -- so Thanks for bearing with me. Feel free to close the issue if you'd agree with the above.
