### ISSUE TITLE
how to integrate provider with openssl no-shared static build

### ISSUE THREAD

**Issue by vkosuri** [open-quantum-safe/oqs-provider#319]
Currently the fullbuild.sh https://github.com/open-quantum-safe/oqs-provider/blob/main/scripts/fullbuild.sh#L54 is configuring openssl without no-shared.

I tried to build openssl static with no-shared, build provider.so, and try to do it's not listing any oqs provider. Ami I missing anything here?

OPENSSL_MODULES=. ./openssl-static list -provider oqsprovider -verbose

**Comment by baentsch** [comment]
I'm not sure I fully understand the question: Do you want to build a static binary for openssl that _contains_ `oqsprovider` without changing the Makefile structures of `openssl`? If so, I wouldn't know how that should be possible: For example, `openssl` does not know where the code for `oqsprovider` needs to be linked into (and I don't know that either). Maybe this is a question for [openssl](https://github.com/openssl/openssl/discussions/new?category=q-a)? Maybe also helpful could be https://github.com/openssl/openssl/discussions/21410

**Comment by baentsch** [comment]
Closing without further input received. Please re-open if new information is available (or comment with your solution if you found one for the benefit of others), @vkosuri
