### ISSUE TITLE
Interoperability with oqs-openssl?

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-provider#32]
Unlike OpenSSL 1.1.1, [OpenSSL3.0 permits EVP keys that do not have both public and private key material](https://github.com/openssl/openssl/issues/16704). Therefore, supporting only "half" PK key pairs as EVP keys makes sense. This also allows for loading (and storing) "true" private EVP OQS keys now. This in turn in in contrast with the oqs-openssl [implementation of storing (persisting) public key material together with private key material](https://github.com/open-quantum-safe/openssl/blob/8c93484150cb30debce06db7289c563d97eaafdb/crypto/ec/oqs_meth.c#L1037-L1038).

This issue is about discussing whether we should (also) do this in oqs-provider, ensuring interoperability with oqs-openssl-generated (persistent) data or whether we want to be more efficient and only store private key material in oqs-provider EVP keys, but thus breaking interoperability between oqs-provider and oqs-openssl(1.1.1). 

The question also will be how to match private and public keys via the provider: Simply comparing key material (as is possible now), doing actual sign/verify operations, or some "hybrid" (hashing) based approach. Example code currently [here](https://github.com/open-quantum-safe/oqs-provider/blob/12fc72cd21cf6735016aff58d5fa40ee6b4fb6b2/oqsprov/oqs_kmgmt.c#L101-L145).

Already extending the feature set is that oqs-provider supports more hybrid KEM mechanisms. But for full TLS signature operations oqs-openssl will remain more relevant until https://github.com/openssl/openssl/issues/10512 is resolved thus making interoperability between oqs-openssl and oqs-provider desirable for users (of most functionality and future-proof OpenSSL).

Thoughts welcome, @dstebila @christianpaquin

**Comment by bhess** [comment]
> We then "just" need to have an RFC for that for all QSC schemes...

I also think this could be addressed after the Internet draft on key serialization is published (perhaps for a next milestone after a November release).

Until that perhaps keep it with the current scheme to not complicate things.

**Comment by bhess** [comment]
This is a reminder that the use of RSA PKCS#1 v1.5 padding (for hybrid signatures) is something to reconsider (see #40):

**Comment by baentsch** [comment]
Maintenance/"dev care and attention" of/for oqs-openssl111 seems to be less than that of oqs-provider (see for example https://github.com/open-quantum-safe/liboqs/issues/1331#issuecomment-1379621934). Therefore dependence on interop with oqs-openssl seems wasteful. Thus this comment is to suggest dropping this issue. Objections anyone?
