### ISSUE TITLE
How to integrate  a new algorithm in openssl-OQS-OpenSSL_1_1_1_stable

### ISSUE THREAD

**Issue by nogogame** [open-quantum-safe/oqs-provider#320]
I have modified lots of files in openssl-OQS-OpenSSL_1_1_1_stable to integrate a algorithm, but it couldn't find out my algorithm's oid. When I assign the oid of  my algorithm, it will not finish the commad app/s_time. While the command line outputs  pause at "Collecting connection statistics for 30 seconds." But if I use kyber and other pqc algorithms, it will show  complete execution. I don't know why, I want to know if I want to integrate a algorithm, what do I need to do. Thank you very much!

**Comment by nogogame** [comment]
I have added my algorithm in these files but I don't know whether it's right to do this and I eager to know if there are some files that I haven't found that need to be modified too. Please let me know,thank you!
Files that I have modified: t1_trce.c ,t1_lib.c ,s_cb.c ,ec/oqs_meth.c ,include/openssl/obj_mac.h ,objects.txt ,evp.h.

**Comment by baentsch** [comment]
Support for OpenSSL111 has ended. Our project does not support changing OpenSSL core files as you list above, but only uses the [OpenSSL provider extension mechanism](https://www.openssl.org/docs/manmaster/man7/provider.html). Please check whether that does what you want.

**Comment by nogogame** [comment]
Thank you.  I have figured out what the problem is and I have successully integrated our algorithm in it and it run successfully.

**Comment by baentsch** [comment]
> Thank you. I have figured out what the problem is and I have successully integrated our algorithm in it and it run successfully.

Thanks for letting us know. Would you mind telling us what algorithm it is? Could you consider contributing the implementation to this project for everyone's benefit?
