### ISSUE TITLE
Issue while Creating keys and certificates

### ISSUE THREAD

**Issue by MEAMITBHOWMICK** [open-quantum-safe/oqs-provider#332]
**Describe the bug**
I am getting this warning : generating random key material may take a long time
if the system has a poor entropy source
No OpenSSL randomness retrieved. DRBG available?

while I run this command from the terminal : openssl req -x509 -new -newkey dilithium2 -keyout dilithium3_CA.key -out dilithium3_CA.crt -nodes -subj "/CN=test CA" -days 365 -config /home/amit/softwares/openssl-1.1.1w/apps/openssl.cnf 

also, any file is not generated in the directory, can anyone please help me on how to solve this issue?

**Comment by baentsch** [comment]
Please read [USAGE.md](https://github.com/open-quantum-safe/oqs-provider/blob/main/USAGE.md):

> Note: Be sure to always activate either the "default" or "fips" provider as these deliver functionality also needed by oqsprovider (e.g., for hashing or high quality random data during key generation).
