### ISSUE TITLE
on replacing a pqc algorithm with a custom implementation

### ISSUE THREAD

**Issue by seschu** [open-quantum-safe/oqs-provider#340]
Hi there,

my question is I think related to the provider concept in generel and I'd like to apologize in advance if you think this is not the right place to ask this.
If I want to "replace" one of the pqc kem algos with a custom lets say hardware accelerated implementation, I could probably just write my own custom provider. But would it still be possible to use the implemented hybrid schemes between pqc and classic algorithms (forex ample kyber and elliptic curves)?

Thanks, Sebastian

**Comment by baentsch** [comment]
> would it still be possible to use the implemented hybrid schemes between pqc and classic algorithms (forex ample kyber and elliptic curves)?

No. The hybrid logic is "tacked-on" to the algorithms provided via `liboqs`. That said, if you'd consider adding a HW-accelerated algorithm to [liboqs](https://github.com/open-quantum-safe/liboqs) you'd save the effort of implementing your own provider _and_ get hybrid support for free (as soon as that algorithm is activated via [the oqs-provider code generator](https://github.com/open-quantum-safe/oqs-provider/blob/main/CONFIGURE.md#pre-build-configuration)).

**Comment by seschu** [comment]
thanks for the swift reply, I really appreciate it! But looking at liboqs my current understanding is that for another HW accelerated for lets say sntrup761, I would add additional code employing my HW accelerator and set the compiler flags so that only that algorithm is used when sntrup761 is used? Or is it possible to choose over the oqs provider whether to use the HW accelerated function or the standard implementation (or avx2).

**Comment by baentsch** [comment]
> I would add additional code employing my HW accelerator and set the compiler flags so that only that algorithm is used when sntrup761 is used?

Yup -- that's how I'd do it.

> Or is it possible to choose over the oqs provider whether to use the HW accelerated function or the standard implementation (or avx2).

Not really: `oqsprovider` links in (shared or static) `liboqs` in whichever config it has been built.

That said, "sntrup761" is only temporarily supported in `liboqs` because it's not proceeding through standardization but only used in `openssh`, so support may be removed in the not-too-distant future. Can I ask why you want to use/enhance with HW support this algorithm?

**Comment by baentsch** [comment]
Suggest to close without further input. No action needed/possible in this project.

**Comment by seschu** [comment]
> That said, "sntrup761" is only temporarily supported in `liboqs` because it's not proceeding through standardization but only used in `openssh`, so support may be removed in the not-too-distant future. Can I ask why you want to use/enhance with HW support this algorithm?

Your curiosity is understandable. It is just for demonstrating a PQC algorithm with hardware acceleration building on existing assets taht should be used. As long as the current versions of the main work with these algos we are happy. Anyway thanks for your help!
