### ISSUE TITLE
No OpenSSL randomness retrieved. DRGB available?

### ISSUE THREAD

**Issue by yacoubhanna** [open-quantum-safe/oqs-provider#343]
Hello, 

I installed OpenSSL 3.2 from GitHub and built the oqs-provider that comes with it. I followed the command in usage file [https://github.com/open-quantum-safe/oqs-provider/blob/main/USAGE.md](url) and while creating the PQ certificates I got an error about randomness retrieved. 

Attached are the screenshots of the commands I used and the errors that I got. 

![Screenshot from 2024-01-25 13-22-52](https://github.com/open-quantum-safe/oqs-provider/assets/50341736/4166d399-9963-4da8-b2bc-fcc85aef4e72)
![Screenshot from 2024-01-25 13-23-10](https://github.com/open-quantum-safe/oqs-provider/assets/50341736/2f7f5658-6e0b-436e-9956-a48e21d78822)

**Comment by baentsch** [comment]
Please re-read USAGE.md:

> Note: Be sure to always activate either the "default" or "fips" provider as these deliver functionality also needed by oqsprovider (e.g., for hashing or high quality random data during key generation).

The error message reported is an indication that none of these providers is active when your code runs. Your logs above confirm this. Activate either and the problem will be gone.
