### ISSUE TITLE
oqs-provider with openssl speed command - unknown algorithm

### ISSUE THREAD

**Issue by dalibor-rada** [open-quantum-safe/oqs-provider#385]
**Describe the bug**
Cannot use the openssl speed command for postquantum algorithms supported via liboqs with oqs-provider.

**To Reproduce**
Have a fresh Ubuntu 22.04.3 LTS
liboqs
     $ sudo apt install astyle cmake gcc ninja-build libssl-dev python3-pytest python3-pytest-xdist unzip xsltproc doxygen graphviz 
     python3-yaml valgrind
     $ git clone -b main https://github.com/open-quantum-safe/liboqs.git
     $ cd liboqs
     $ mkdir build && cd build
     $ cmake -GNinja ..
     $ ninja
     $ ninja install
oqs-provider
     download and unzip latest version 0.5.3
     $ cd into_oqs-provider_folder
     $ scripts/fullbuild.sh
     $ scripts/runtests.sh
     $ cmake --install _build
     edit the openssl.cnf file (https://github.com/open-quantum-safe/oqs-provider/blob/main/USAGE.md#activation, section 
     Configuration file)
     $ openssl speed kyber512

**Expected behavior**
This set of commands should led to the benchmark of postquantum algorithms via openssl speed command.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - OpenSSL version 3.0.2
 - oqsprovider version 0.5.3

**openssl version**
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
**openssl list -providers**
providers:
default
name: OpenSSL Default Provider
version: 3.0.2
status: active
oqsprovider
name: OpenSSL OQS Provider
version: 0.5.3
status: active

![image](https://github.com/open-quantum-safe/oqs-provider/assets/162028714/89d63cf6-91bf-475b-8c15-9aad5dc5a369)
![image](https://github.com/open-quantum-safe/oqs-provider/assets/162028714/7a9cc688-5cd1-443b-aa67-f9b3adf969c7)

the runtest.sh script output this:
Test setup:
LD_LIBRARY_PATH=/home/student/oqs-provider-0.5.3/.local/lib
OPENSSL_APP=openssl
OPENSSL_CONF=/home/student/oqs-provider-0.5.3/scripts/openssl-ca.cnf
OPENSSL_MODULES=/home/student/oqs-provider-0.5.3/_build/lib
Version information:
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
Providers:
  default
    name: OpenSSL Default Provider
    version: 3.0.2
    status: active
    build info: 3.0.2
    gettable provider parameters:
      name: pointer to a UTF8 encoded string (arbitrary size)
      version: pointer to a UTF8 encoded string (arbitrary size)
      buildinfo: pointer to a UTF8 encoded string (arbitrary size)
      status: integer (arbitrary size)
  oqsprovider
    name: OpenSSL OQS Provider
    version: 0.5.3
    status: active
    build info: OQS Provider v.0.5.3 () based on liboqs v.0.10.1-dev
    gettable provider parameters:
      name: pointer to a UTF8 encoded string (arbitrary size)
      version: pointer to a UTF8 encoded string (arbitrary size)
      buildinfo: pointer to a UTF8 encoded string (arbitrary size)
      status: integer (arbitrary size)
Cert gen/verify, CMS sign/verify, CA tests for all enabled OQS signature algorithms commencing: 
.......................
External interop tests commencing
 Cloudflare:
kex=X25519Kyber768Draft00
kex=X25519Kyber512Draft00
Test project /home/student/oqs-provider-0.5.3/_build
    Start 1: oqs_signatures
1/5 Test #1: oqs_signatures ...................   Passed   10.81 sec
    Start 2: oqs_kems
2/5 Test #2: oqs_kems .........................   Passed    0.73 sec
    Start 3: oqs_groups
3/5 Test #3: oqs_groups .......................   Passed    1.06 sec
    Start 4: oqs_tlssig
4/5 Test #4: oqs_tlssig .......................   Passed    0.01 sec
    Start 5: oqs_endecode
5/5 Test #5: oqs_endecode .....................   Passed   28.83 sec

100% tests passed, 0 tests failed out of 5

Total Test time (real) =  41.44 sec

All oqsprovider tests passed.

**Comment by dalibor-rada** [comment]
Hello, 

thank you for you answer. I appreciate it. I did the installation again. Again the same problem. I checked the openssl list -kem-algorithms command, and it says just the same as you said it should: 
![image](https://github.com/open-quantum-safe/oqs-provider/assets/162028714/b432371c-d889-4bf6-8163-5aa42df39b3c)
but, then openssl speed remains the same:
![image](https://github.com/open-quantum-safe/oqs-provider/assets/162028714/75dbe8d3-2f5b-480c-a90a-0e8c6cfdf5d4).

I have no idea what to do. There's another screen - of the openssl.cnf file:
![image](https://github.com/open-quantum-safe/oqs-provider/assets/162028714/2f0d3c56-7aa7-49db-b3bf-c11dbe2124a1).

I'd be grateful for any further advice, please.

**Comment by dalibor-rada** [comment]
UPDT: I tried the same procedure on Debian, and got the same error with unknown algorithm. Am I really doing the right thing?

**Comment by baentsch** [comment]
I think you do (the right thing). The only idea I have left is that you should try running a more recent openssl version: 3.0.2 has _many_ problems wrt Providers...

**Comment by dalibor-rada** [comment]
Yep, you're right. Upgrade to OpenSSL 3.2.1 helped. Thank you for effort :)
