### ISSUE TITLE
conduct 'Full stack' performance testing using standard client software like 'curl' and nginx as the Web Server

### ISSUE THREAD

**Issue by sckhg1367** [open-quantum-safe/oqs-provider#389]
I'd like to conduct 'Full stack' performance testing using standard client software such as 'curl' and 'nginx' as the Web Server. Could you please advise me on how to get started? Thank you.

**Comment by baentsch** [comment]
Thanks for your interest using, maybe contributing to the project. We already do something very similar in the [profiling](https://github.com/open-quantum-safe/profiling) sub project, most notably [here](https://github.com/open-quantum-safe/profiling/blob/main/perf/scripts/handshakes.py). It may be easiest for you to swap out the `openssl s_server` calls there with setup calls to a PQ-enabled `nginx` (e.g., following [this code](https://github.com/open-quantum-safe/oqs-demos/tree/main/nginx)).

Also tagging @SWilson4 for further input as he volunteered to revamp the current `profiling` code.

**Comment by baentsch** [comment]
As this is no (code) problem/issue, converting to discussion.
