### ISSUE TITLE
Update SPECIFICATIONS.md

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-provider#396]
This file may need some enhancement since landing #317, do you agree @feventura ? Will do myself when back again.

**Comment by feventura** [comment]
Hi @baentsch , I'm struggling to find the SPECIFICATIONS.md to understand what you mean by enhancement.
Where it should be?

**Comment by baentsch** [comment]
>  struggling to find the SPECIFICATIONS.md

My bad, sorry, I meant STANDARDS.md.
