### ISSUE TITLE
Error initializing dilithium2 context

### ISSUE THREAD

**Issue by SangeethaPH** [open-quantum-safe/oqs-provider#421]
**Describe the bug**
Error initializing dilithium2 context

**Context**
I am trying out openssl3 library with oqs-provider. Compilation of liboqs, openssl3 & provider repo went fine without error.
When I try to test new algorithm support I hit below error 
```
root@08cb12f91199:~/quantumsafe# /usr/local/openssl3/bin/openssl genpkey -algorithm dilithium2 -out private_key.pem
Error initializing dilithium2 context
C0E43899FF7E0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:355:Global default library context, Algorithm (dilithium2 : 0), Properties (<null>)
```

**To Reproduce**
reffered below doc to  link all three libraries
[link](https://developer.ibm.com/tutorials/awb-quantum-safe-openssl/)

**Expected behavior**
Expecting enc/decrypt to go smoothly with new openssl3

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20]
 - OpenSSL version [e.g., 3.2.0-dev]
 - oqsprovider version [e.g. 0.4.0]

Please run the following commands to obtain the version information:
 - For OpenSSL: `openssl version` 
 - For oqsprovider: `openssl list -providers`

If `oqsprovider` is not listed as active, be sure to first follow all
[USAGE guidance](https://github.com/open-quantum-safe/oqs-provider/blob/main/USAGE.md).

If reporting bugs triggered by OpenSSL API integrations, e.g. running
a provider build [statically](https://github.com/open-quantum-safe/oqs-provider/blob/main/CONFIGURE.md#oqs_provider_build_static)
or directly invoking any OpenSSL API, be sure to retrieve and report all errors
reported by using the OpenSSL [ERR_get_error_all](https://www.openssl.org/docs/man3.1/man3/ERR_get_error_all.html)
function.

Bug reports generated from [Debug builds](https://github.com/open-quantum-safe/oqs-provider/wiki/Debugging)
wth the debug environment variable "OQSPROV=1" set will be particularly helpful to find underlying
problems.

**Additional context**

**Hints**
To exclude a build/setup error, please consider running your test
commands to reproduce the problem in our [pre-build docker image](https://hub.docker.com/repository/docker/openquantumsafe/oqs-ossl3/general),
e.g. as such: `docker run -it openquantumsafe/oqs-ossl3` and
provide full command input and output traces in the bug report.

**Comment by baentsch** [comment]
Sorry for seeing this only now (hoping I'm not the only person interested in oqs-provider :-/). 

Your problem with most certainty has to do with a missing activation of `oqs-provider` (wrong paths to OPENSSL_CONFIG, maybe?). You can confirm this if providing the output of `openssl list -providers` as requested in the bug report (but left empty above). Please note that the link you provided above leads to a proprietary blog we do not maintain and do not debug if it leads to errors. Please be sure to ask for help there.

If you just want a working system, please use our [docker images, e.g. the one for oqs-enabled curl](https://hub.docker.com/repository/docker/openquantumsafe/curl/general): They're certain to work without the need to build anything.

**Comment by baentsch** [comment]
Closing as no further feedback is received. @SangeethaPH please re-open if you have updates to share.
