### ISSUE TITLE
OpenSSL Git Link in fullbuild.sh

### ISSUE THREAD

**Issue by samettonyali** [open-quantum-safe/oqs-provider#422]
**Describe the bug**

**To Reproduce**
Build oqs-provider using fullbuild.sh

**Expected behavior**
Download the repo smoothly

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 24.04
 - OpenSSL version 3.3
 - oqsprovider version 0.6.0 - main branch

**Additional context**
I don't know if I am the only one who faces this problem because I searched it in the issues but couldn't see anyone complaining about it. When I use scripts/fullbuild.sh with openssl-3.3 branch (given as an environment var) it cannot clone the relevant branch, and the connection times out after a while. I changed the link from "git://git.openssl.org/openssl.git" to "https://git.openssl.org/openssl.git" and it worked. BTW, to download liboqs the script uses the link with https protocol, but I don't know why this link for openssl starts with a "git". It may or may not be a bug, but I wanted to report it anyways.

**Hints**
To exclude a build/setup error, please consider running your test
commands to reproduce the problem in our [pre-build docker image](https://hub.docker.com/repository/docker/openquantumsafe/oqs-ossl3/general),
e.g. as such: `docker run -it openquantumsafe/oqs-ossl3` and
provide full command input and output traces in the bug report.

**Comment by baentsch** [comment]
Thanks for the report, @samettonyali ! Indeed, using "git://..." isn't a good choice (outside of a fully `github` enabled environment). Would you want to submit a PR to fix this or do you prefer us to implement your proposal?

**Comment by baentsch** [comment]
Update @samettonyali : I have to fix this myself as the same problem now manifests itself in our CI system. Thanks for the heads-up anyway!
