### ISSUE TITLE
Dilithium cert is not recognized

### ISSUE THREAD

**Issue by HarryLee02** [open-quantum-safe/oqs-provider#425]
I followed this [link](https://developer.ibm.com/tutorials/awb-building-quantum-safe-web-applications/) and got to the starting TLS server step. But it seems that openssl doesnt recognize dilithium cert type. After I run this line
```
$ openssl s_server -cert server.crt -key server.key -www -tls1_3 -CAfile CA.crt -curves kyber512:p521_kyber1024
```
I got the error:
```
Using default temp DH parameters
error setting certificate
40D7675D127C0000:error:0A0000F7:SSL routines:ssl_set_cert:unknown certificate type:../ssl/ssl_rsa.c:239:
```
My openssl version does have oqsprovider:
```bash
$ openssl version
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

$ openssl list -providers -verbose -provider oqsprovider
Providers:
  default
    name: OpenSSL Default Provider
    version: 3.0.2
    status: active
    build info: 3.0.2
    gettable provider parameters:
      name: pointer to a UTF8 encoded string (arbitrary size)
      version: pointer to a UTF8 encoded string (arbitrary size)
      buildinfo: pointer to a UTF8 encoded string (arbitrary size)
      status: integer (arbitrary size)
  oqsprovider
    name: OpenSSL OQS Provider
    version: 0.6.1-dev
    status: active
    build info: OQS Provider v.0.6.1-dev (8b3d460) based on liboqs v.0.10.1-dev
    gettable provider parameters:
      name: pointer to a UTF8 encoded string (arbitrary size)
      version: pointer to a UTF8 encoded string (arbitrary size)
      buildinfo: pointer to a UTF8 encoded string (arbitrary size)
      status: integer (arbitrary size)
```
I don't even know where is the ..ssl/ssl_rsa.c is so I don't know what to debug.
I have followed the previous step correctly, only the `curl` does not recognize kyber or dilithium, and it only displayed `SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384`. I think this is not relevant but will mention it anyway

**Comment by bhess** [comment]
Hi @HarryLee02, I think you need at least OpenSSL v3.2 for full PQ-TLS support, see https://github.com/open-quantum-safe/oqs-provider/blob/main/README.md#32-and-greater.
