### ISSUE TITLE
Not able to decrypt certificate private key (generated using PQC algorithm)  

### ISSUE THREAD

**Issue by aniket-rulez** [open-quantum-safe/oqs-provider#438]
Hi, we have a requirement to support PQC algorithms for certificate generation and the current code is executing the following commands to decrypt the private key:

`openssl rsa -in <encfile> -out <plainfile>`
`openssl ec -in <encfile> -out <plainfile>`

Also, later, for pkcs12 format, the keys are being sanitised using the below commands:

`openssl rsa -in <plainfile> -out <encfile> -aes256`
`openssl ec -in <plainfile> -out <encfile> -aes256`

I tried to do something similar for PQC algorithms but options only supported rsa and ec, so I wanted to check if there is something similar available for PQC algorithms also to perform the above operations. 

Thanks in advance!

**Comment by baentsch** [comment]
Did you already try out the [openssl pkey command](https://www.openssl.org/docs/manmaster/man1/openssl-pkey.html) as per the `openssl rsa` command documentation

> The [openssl-pkey(1)](https://www.openssl.org/docs/manmaster/man1/openssl-pkey.html) command is capable of performing all the operations this command can, as well as supporting other public key types.

?

**Comment by aniket-rulez** [comment]
This works, thanks for the help!
