### ISSUE TITLE
Not able to read dilithium private key using PEM_read_bio_PrivateKey routine 

### ISSUE THREAD

**Issue by aniket-rulez** [open-quantum-safe/oqs-provider#443]
I was trying to read the private key generated using dilithium with "PEM_read_bio_PrivateKey" routine but it's returning null ptr. On adding error routines to check what went wrong, we got the following output:

ERR_peek_last_error() => 50331766
ERR_error_string(ERR_get_error(), NULL) => error:1E08010C:DECODER routines::unsupported

Kindly help with how we can achieve the same for PQC signature algorithms. Thanks in advance!

**Comment by baentsch** [comment]
I'm afraid I don't have the bandwidth to recreate your setup manually. Just looking at the error message, I'd _guess_ that `oqsprovider` is not active thus leading to an "unsupported" output. Conceptually, it should work as these APIs are used in the more high level (private key en/decoding) tests we have for `oqsprovider`.

My recommendation is you debug into the calls into the `openssl` code to find out why/where NULL is returned. Another proposal is to raise the question in the `openssl` community as this is not an API maintained within `oqsprovider`.

**Comment by beldmit** [comment]
@aniket-rulez could you please check that oqsprovider is loaded?

**Comment by baentsch** [comment]
Closing without further input received. Assuming issue is resolved when `oqsprovider` is correctly loaded. @aniket-rulez please re-open if you have further news to report.

**Comment by aniket-rulez** [comment]
Hi @baentsch and @beldmit, thanks for your inputs! The oqsprovider was not being loaded correctly and after the load, the issue was resolved.
