### ISSUE TITLE
Can't cross compile on Linux for Windows

### ISSUE THREAD

**Issue by maroueneboubakri** [open-quantum-safe/oqs-provider#445]
Hello,

Taking library version 0.6.1

I'm expecting that setting the toolchain file to `.CMake/toolchain_windows_amd64.cmake` should suceed.

However:

```
CMake Error at CMakeLists.txt:21 (project):
  Generator

    Ninja

  does not support platform specification, but platform

    x64

  was specified.


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

My env:

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"


$ ninja --version
1.10.0

$ cmake --version
cmake version 3.27.7
```

What is wrong with this ?

I raised the issue here as well https://github.com/open-quantum-safe/liboqs/issues/1826 I suspect an issue with the environment, therefore, I suggest to properly set minimal versions required of CMake, Minja etc in the project.

Br
Maro

**Comment by SWilson4** [comment]
As in open-quantum-safe/liboqs#1826, this toolchain is not meant to be used for cross-compiling but rather for building on Windows. See line 7:
https://github.com/open-quantum-safe/oqs-provider/blob/8f37521d5e27ab4d1e0d69a4b4a5bd17927b24b9/.CMake/toolchain_windows_amd64.cmake#L7
