### ISSUE TITLE
Convert EVP_PKEY to uint8_t

### ISSUE THREAD

**Issue by xianglingzhang** [open-quantum-safe/oqs-provider#449]
I want to input the public key in a certificate into the interface

`OQS_KEM_encaps(const OQS_KEM *kem, uint8_t *ciphertext, uint8_t *shared_secret, const uint8_t *public_key)`

but it is "EVP_PKEY" type, so how to convert it to "uint8_t" ?

**Comment by baentsch** [comment]
Extracting public key material from an `openssl` data structure is an OpenSSL question and has nothing to do with OQS(provider).
