### ISSUE TITLE
Example of adding more hybrid algorithms to generate.yaml

### ISSUE THREAD

**Issue by maroueneboubakri** [open-quantum-safe/oqs-provider#453]
> is there any change to make this combination through the template generator 

> Yes, this should work -- but please note that this would be a hybrid, not a composite (edit/add: Please check the README at the link above to see the differences). If you're _really_ after a Composite, I'd suggest touching base with @feventura who contributed that code).

_Originally posted by @baentsch in https://github.com/open-quantum-safe/oqs-provider/issues/426#issuecomment-2161108300_
            
Hello @baentsch  When I try to add for example `rsa4096_dilithium3 `or `rsa3072_dilithium3` or `pss4096_dilithium3` to `generate.yaml`, and I create a key/certificate the generated classic key is always rsa2048, while for `p521_dilithium3` or `p256_dilithium3` it always generates p384 for classic part. 

Is there anything besides this or the approach itself is not good and simply can't add those combinations ?

Br
Maro

**Comment by baentsch** [comment]
Please post your changes to generate.yml, what exactly you then executed (generate/build/execute), what you expected and what actually happened (as well as the platform used, of course).

**Comment by maroueneboubakri** [comment]
Thanks
