### ISSUE TITLE
Various warnings building OQS Provider on Mac

### ISSUE THREAD

**Issue by ashman-p** [open-quantum-safe/oqs-provider#467]
I am hitting various complier warnings building oqs-provider on my Mac.
I have a patch file that addresses these warnings. If worthwhile I can create a PR for this.
 
A sample of them includes....
cmake -S . -B _build && cmake --build _build && ctest --test-dir _build && cmake --install _build

- CMake Deprecation Warning at CMakeLists.txt:4 (cmake_minimum_required):

  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

- oqsprov/oqs_sig.c:221:5: warning: initializing 'const unsigned char *' with an expression of type 'char[27]' converts between pointers to integer types where one is of the unique plain 'char' type and the other is not [-Wpointer-sign]

    "060B6086480186FA6B50080101", // mldsa44_pss2048
[-Wpointer-sign]

- oqsprov/oqs_sig.c:485:62: warning: passing 'char *' to parameter of type 'const uint8_t *' (aka 'const unsigned char *') converts between pointers to integer types where one is of the unique plain 'char' type and the other is not [-Wpointer-sign]

                if (OQS_SIG_sign(oqs_key, buf, &oqs_sig_len, final_tbs,

- oqsprov/oqs_kem.c:241:18: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]

    if ((evp_ctx == NULL)) {

[oqs_prov_warnings_fix.patch](https://github.com/user-attachments/files/16505610/oqs_prov_warnings_fix.patch)

**Comment by baentsch** [comment]
Thanks for this report @ashman-p . Of course, a PR is always welcome. Best would be if it came with CI demonstrating the fix (fails before, passes afterwards), making (CI of) the project more robust.
