### ISSUE TITLE
Missing Composite documentation

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-provider#475]
When browsing the list of [supported sig algorithms](https://github.com/open-quantum-safe/oqs-provider/blob/main/oqs-template/oqs-sig-info.md) it became apparent that the composite algs are not listed. Intention or omission @feventura ? If the latter, would you have time to fix or should I look into this?

**Comment by feventura** [comment]
Its the second one, I forgot to add composite to that list. I'll work on it.

**Comment by baentsch** [comment]
Closed via #549
