### ISSUE TITLE
oqs-provider debian package lists statically linked liboqs as a requirement

### ISSUE THREAD

**Issue by fwh-dc** [open-quantum-safe/oqs-provider#491]
### Thank you for taking the time to share your thoughts with us.

https://github.com/open-quantum-safe/oqs-provider/blob/a0f475daba6dcbe3088ff8943810d15cecd2c971/oqsprov/CMakeLists.txt#L97

It should not be necessary to list liboqs as a dependency when liboqs is built and linked as a static library?

**Comment by baentsch** [comment]
> It should not be necessary to list liboqs as a dependency when liboqs is built and linked as a static library?

That is a correct observation in my eyes -- and thus a bug in this line. As far as I remember I added this line before diving deeper into static building (reminds me I still need to complete #367)...

Thanks for the heads-up @fwh-dc !

**Comment by fwh-dc** [comment]
Should I make a PR for it or do you want to do it?

**Comment by baentsch** [comment]
> Should I make a PR for it or do you want to do it?

If you'd have time, I'd gladly review the contribution.
