### ISSUE TITLE
Cannot use dilithium certificates with s_server

### ISSUE THREAD

**Issue by fwh-dc** [open-quantum-safe/oqs-provider#492]
**To Reproduce**

I am trying to run the commands from the USAGE.md:
```
openssl req -x509 -new -newkey dilithium3 -keyout dilithium3_CA.key -out dilithium3_CA.crt -nodes -subj "/CN=test CA" -days 365 -provider oqsprovider -provider default
openssl genpkey -algorithm dilithium3 -out dilithium3_srv.key -provider oqsprovider -provider default
openssl req -new -newkey dilithium3 -keyout dilithium3_srv.key -out dilithium3_srv.csr -nodes -subj "/CN=test server" -provider oqsprovider -provider default 
openssl x509 -req -in dilithium3_srv.csr -out dilithium3_srv.crt -CA dilithium3_CA.crt -CAkey dilithium3_CA.key -CAcreateserial -days 365  -provider oqsprovider -provider default
```

Which reports:
```
Certificate request self-signature ok
subject=CN = test server
```

But when I use it with
```
openssl s_server -cert dilithium3_srv.crt -key dilithium3_srv.key -tls1_3 -groups kyber768:frodo640shake -provider oqsprovider -provider default
```

It reports:
```
Using default temp DH parameters
error setting certificate
40F7C41E717F0000:error:0A00018E:SSL routines:SSL_CTX_use_certificate:ca md too weak:../ssl/ssl_rsa.c:221:
```

**Environment (please complete the following information):**
 - OS: debian 12
 - OpenSSL 3.0.13
 - oqsprovider version 0.5.3

**Comment by baentsch** [comment]
Sincere apologies, @fwh-dc : I wrote text explaining the label change yesterday, but this apparently didn't get posted: 

The behaviour above is absolutely expected, as OpenSSL3.0.13 cannot handle provider-based TLS signature algorithms. This is documented in https://github.com/open-quantum-safe/oqs-provider/?tab=readme-ov-file#note-on-openssl-versions

**Comment by fwh-dc** [comment]
Great! Would you accept a PR where I made this clear in the USAGE.md?

**Comment by baentsch** [comment]
Certainly. Anyone (proactively) _doing_ stuff, helping the community, is very welcome!
