### ISSUE TITLE
Compilation error: undefined reference to symbol 'pthread_once@@GLIBC_2.2.5'

### ISSUE THREAD

**Issue by fwh-dc** [open-quantum-safe/oqs-provider#528]
**Describe the bug**

When building with latest main on oqs-provider and latest main liboqs the linker complains of missing symbols.

```
19:06:38  [31/33] Linking C executable examples/example_static_oqsprovider
19:06:38  FAILED: examples/example_static_oqsprovider 
19:06:38  : && /usr/bin/cc -g  examples/CMakeFiles/example_static_oqsprovider.dir/static_oqsprovider.c.o -o examples/example_static_oqsprovider  -Wl,-rpath,/source/build/debug/debian/x86_64/install/lib  /source/build/debug/debian/x86_64/install/lib/libcrypto.so  lib/liboqsprovider.a  lib/liboqsprovider.a  /source/build/debug/debian/x86_64/install/lib/liboqs.a  /source/build/debug/debian/x86_64/install/lib/libcrypto.so && :
19:06:38  /usr/bin/ld: /source/build/debug/debian/x86_64/install/lib/liboqs.a(common.c.o): undefined reference to symbol 'pthread_once@@GLIBC_2.2.5'
19:06:38  /usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
19:06:38  collect2: error: ld returned 1 exit status
```

I don't know if dependencies can/should be automatically "transferred" by cmake?

We are using cmake external project to handle 3rd party builds.

**Environment (please complete the following information):**
 - OS: Debian 11.
 - OpenSSL version [e.g., 3.2.0-dev]
 - oqsprovider version: main ([ea7d18d](https://github.com/open-quantum-safe/oqs-provider/commit/ea7d18d179518ca9e8e0dc6005d89eb728dd42ae))

**Comment by SWilson4** [comment]
Hi @fwh-dc, thanks for the report. Could you please provide the commands you used to build liboqs and oqs-provider so that I can try to reproduce this error?

**Comment by fwh-dc** [comment]
Our setup is a bit complex so I've tried to find a minimal example. But I have failed to do so. So I guess it is something in our setup that breaks it. I think we should just close this one and then I can reopen it if get an epiphany.

**Comment by fwh-dc** [comment]
One thing I notice is:

We use docker compose for our debian builds. If I switch from debian 11 to debian 12 in the Dockerfile then things compiles as expected.
