### ISSUE TITLE
Issue with Loading oqsprovider.so on Android using OSSL_PROVIDER_load

### ISSUE THREAD

**Issue by moganty** [open-quantum-safe/oqs-provider#536]
I have successfully built oqsprovider.so for the ARM64 architecture, along with its dependencies: libcrypto, libssl, and liboqs. However, I am encountering an issue during runtime where OSSL_PROVIDER_load fails to load oqsprovider.

I am currently working on an Android build and would greatly appreciate any suggestions or guidance on how to resolve this issue.

Here are some specifics:

I have verified that all the required libraries are correctly built and present in the appropriate directories.
The native code is integrated with my Android application using the NDK.
If anyone has experience with using OQS Provider on Android or insights into the loading mechanism of shared libraries in this context, your input would be invaluable.

Thank you for your help!

**Comment by moganty** [comment]
Hi @ashman-p , I am loading the provider programmatically in an Android application. I have created an NDK module where I added my code to load the provider.

**Here is the code:**

 ```
OSSL_LIB_CTX *libctx = initialize_openssl(confPath, "oqsprovider");

// Function to initialize OpenSSL and load necessary providers
OSSL_LIB_CTX *initialize_openssl(const char *config_path, const char *provider_name) {
    OSSL_LIB_CTX *libctx = OSSL_LIB_CTX_new();
    if (!libctx) {
       // fprintf(stderr, "Error creating OpenSSL library context\n");
        return NULL;
    }

    if (!OSSL_LIB_CTX_load_config(libctx, config_path)) {
       // fprintf(stderr, "Error loading OpenSSL configuration\n");
        OSSL_LIB_CTX_free(libctx);
        return NULL;
    }

    if (!OSSL_PROVIDER_load(libctx, provider_name)) {
        // fprintf(stderr, "Error loading provider: %s\n", provider_name);
       // Print detailed OpenSSL errors
        while ((err = ERR_get_error()) != 0) {
            char err_msg[256];
            ERR_error_string_n(err, err_msg, sizeof(err_msg));
            //printf("OpenSSL Error: %s\n", err_msg);
            __android_log_print(ANDROID_LOG_ERROR, LOG_TAG,"OpenSSL error:%s",err_msg);
        }
        OSSL_LIB_CTX_free(libctx);
        return NULL;
    }

    return libctx;
}
```


**error log:**

Open SSL error: error:12800067:DSO support routines::could not load the shared library
Open SSL error: error:12800067:DSO support routines::could not load the shared library
Open SSL error: error:07880025:common libcrypto routines::reason(37)
Error loading provider error: error:00000000:lib(0)::reason(0)


**lib folder path in code:**

src/main/jnilibs/arm64-v8a/oqsprovider.so

**file command:**

file oqsprovider.so 

oqsprovider.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=9613443c56c7ae218391ad3415b898478dc517eb, with debug_info, not stripped


Openssl version: 3.3.2

Let me know if you need more info

Thanks

**Comment by ashman-p** [comment]
Hi @moganty, Thanks for providing the info. Lets see if more experienced android developers will chime in.
Its interesting though that your error log was not displayed.
"__android_log_print(ANDROID_LOG_ERROR, LOG_TAG,"OpenSSL error:%s",err_msg);"

**Comment by moganty** [comment]
Thank you, @ashman-p. The provider works perfectly on macOS, but the same code fails on Android. Do you think OpenSSL is failing to load the provider in the Android environment? Or would it be better to post this issue in the OpenSSL forum for further assistance?

**Comment by baentsch** [comment]
> Or would it be better to post this issue in the OpenSSL forum for further assistance?

Before you do that I strongly advise you fill in all information we are asking for in [a bug report](https://github.com/open-quantum-safe/oqs-provider/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=).

I know it is tedious, but a) creating this template was tedious for us too, b) has proven to unearth (and solve) many problems even before an issue is raised and c) would deliver information I'd ask for anyway (incl. in an OpenSSL forum). Thanks.

**Comment by moganty** [comment]
created a bug here. https://github.com/open-quantum-safe/oqs-provider/issues/539

**Comment by baentsch** [comment]
Issue replaced by more detailed report in #539
