### ISSUE TITLE
inconsistent in list kem-algorithms

### ISSUE THREAD

**Issue by vkosuri** [open-quantum-safe/oqs-provider#551]
when listing kem-algorithms it's showing properly for x25519_mlkem512 whereas for 768 it's different X25519MLKEM768

It used to be listed in 0.6.1, it was deviated for 0.7.1-dev.

I think this PR https://github.com/open-quantum-safe/oqs-provider/pull/524/files was introduced to the change.

```bash

root@1c058c8d24df:/package# openssl32 list -providers
Providers:
  default
    name: OpenSSL Default Provider
    version: 3.2.0
    status: active
  oqsprovider
    name: OpenSSL OQS Provider
    version: 0.7.1-dev
    status: active

root@1c058c8d24df:/package# openssl32 list -kem-algorithms | grep 25519
  { 1.3.101.110, X25519 } @ default
  x25519_frodo640aes @ oqsprovider
  x25519_frodo640shake @ oqsprovider
  x25519_kyber512 @ oqsprovider
  x25519_kyber768 @ oqsprovider
  x25519_mlkem512 @ oqsprovider
  X25519MLKEM768 @ oqsprovider
  x25519_bikel1 @ oqsprovider
  x25519_hqc128 @ oqsprovider
root@1c058c8d24df:/package#
```

**Comment by SWilson4** [comment]
Hi @vkosuri, this is intentional. The name was updated to reflect the naming convention used in https://datatracker.ietf.org/doc/draft-kwiatkowski-tls-ecdhe-mlkem/02/. See also https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-8.
