### ISSUE TITLE
I want to know if the OID of mldsa will change

### ISSUE THREAD

**Issue by MMDHBZ** [open-quantum-safe/oqs-provider#554]
Hello, I found the OID of mldsa44 pure sign on the following website “https://csrc.nist.gov/projects/computer-security-objects-register/algorithm-registration” is define as 2.16.840.1.101.3.4.3.17, while the one in the current project is 1.3.6.1.4.1.2.267.12.4.4. I want to confirm whether there is a plan to change it.

**Comment by baentsch** [comment]
Yes; this will be updated as and when the code conforming to the NIST standard gets integrated.
