### ISSUE TITLE
Extract tmp ciphertext from TLS (Kem) handshake

### ISSUE THREAD

**Issue by rauldiazz** [open-quantum-safe/oqs-provider#574]
Is it possible to obtain the temporary encapsulated key from a TLS KEM handshake (like for kyber)?

**Comment by baentsch** [comment]
Anything is possible in software :) Fun aside: I don't see anything PQC/OQS-specific in this question and would consider this an OpenSSL (KEM) functionality question really, so you may want to ask the question [there](https://github.com/openssl/openssl/discussions/categories/q-a), best with a rationale.
