### ISSUE TITLE
Compile error in latest (commit 527e41) 

### ISSUE THREAD

**Issue by wbeck10** [open-quantum-safe/oqs-provider#576]
When building the oqs provider, following error is raised using gcc linux:
 
oqsprov_keys.c:204:33: error: ?OQS_SIG_alg_cross_rsdp_128_balanced? undeclared here (not in a function); did you mean ?OQS_SIG_alg_is_enabled??
     {0, "CROSSrsdp128balanced", OQS_SIG_alg_cross_rsdp_128_balanced,

**Comment by baentsch** [comment]
Did you build against liboqs master (that contains CROSS) or against an old version (that doesn't)?

**Comment by wbeck10** [comment]
I'll check.

**Comment by wbeck10** [comment]
Building against latest liboqs solves this issue.
