### ISSUE TITLE
Signing with dilitium2 with same key, does not produce same signature value

### ISSUE THREAD

**Issue by wbeck10** [open-quantum-safe/oqs-provider#580]
I've wrote following test case which creates a dilithium2 key:
The same message gets signed with same key but with fresh initialized ctx's.
The expected result would be, both signature values are the same.
Current result: memcmp fails due to different signature values. 

    EVP_MD_CTX *mdctx = NULL;
    EVP_PKEY_CTX *ctx = NULL;
    EVP_PKEY *key = NULL;
    const char msg[] = "The quick brown fox jumps over... you know what";
    unsigned char *sig;
    size_t siglen;
    EVP_MD_CTX *mdctx2 = NULL;
    unsigned char *sig2;
    size_t siglen2;
    int ret = 1;

    ctx = EVP_PKEY_CTX_new_from_name(libctx, "dilithium2", NULL);
    EVP_PKEY_keygen_init(ctx) && EVP_PKEY_generate(ctx, &key);

    mdctx = EVP_MD_CTX_new();
    ret = EVP_DigestSignInit_ex(mdctx, NULL, "SHA512", libctx, NULL, key, NULL);
    ret = EVP_DigestSignUpdate(mdctx, msg, sizeof(msg));
    ret = EVP_DigestSignFinal(mdctx, NULL, &siglen);
    sig = OPENSSL_malloc(siglen);
    ret = EVP_DigestSignFinal(mdctx, sig, &siglen);

    mdctx2 = EVP_MD_CTX_new();
    ret = EVP_DigestSignInit_ex(mdctx2, NULL, "SHA512", libctx, NULL, key, NULL);
    ret = EVP_DigestSignUpdate(mdctx2, msg, sizeof(msg));
    ret = EVP_DigestSignFinal(mdctx2, NULL, &siglen2);
    sig2 = OPENSSL_malloc(siglen2);
    ret = EVP_DigestSignFinal(mdctx2, sig2, &siglen2);

    if (siglen != siglen2 || memcmp(sig, sig2, siglen) != 0)
        fprintf(stderr, "Failed, signatures is not same!\n");
    else
        fprintf(stderr, "Signatures is same.\n");

    EVP_MD_CTX_free(mdctx);
    EVP_MD_CTX_free(mdctx2);
    EVP_PKEY_free(key);
    EVP_PKEY_CTX_free(ctx);
    OPENSSL_free(sig);
    OPENSSL_free(sig2);
    mdctx = NULL;
    mdctx2 = NULL;
    key = NULL;

**Comment by baentsch** [comment]
AFAIK, Dilithium2 is configured by default in OQS to use randomized signing, so this result is entirely expected. @bhess?

**Comment by SWilson4** [comment]
> AFAIK, Dilithium2 is configured by default in OQS to use randomized signing, so this result is entirely expected. @bhess?

It is indeed: https://github.com/open-quantum-safe/liboqs/blob/d0d0413dc9fff538296ab86bac492cb4bf54dedb/src/sig/dilithium/CMakeLists.txt#L10
