### ISSUE TITLE
Q: How to generate ML-KEM and ML-DSA key pairs?

### ISSUE THREAD

**Issue by mouse07410** [open-quantum-safe/oqs-provider#589]
I'd like to know how to generate key-pairs for `mlkem1024` and `mldsa87` algorithms, using OpenSSL CLI?

When I try the "dumb" method, it fails:

```text
$ openssl genpkey -algorithm mlkem1024 -out /tmp/prkey.out -outpubkey /tmp/pubkey.out -verbose
Error writing key(s)
804F4656F87F0000:error:1D800065:ENCODER routines:OSSL_ENCODER_to_bio:reason(101):crypto/encode_decode/encoder_lib.c:55:No encoders were found. For standard encoders you need at least one of the default or base providers available. Did you forget to load them?
804F4656F87F0000:error:04800073:PEM routines:do_pk8pkey:error converting private key:crypto/pem/pem_pk8.c:133:
$ openssl list -providers
Providers:
  default
    name: OpenSSL Default Provider
    version: 3.4.0
    status: active
  legacy
    name: OpenSSL Legacy Provider
    version: 3.4.0
    status: active
  oqs
    name: OpenSSL OQS Provider
    version: 0.7.1-dev
    status: active
  pkcs11
    name: PKCS#11 Provider
    version: 3.4.0
    status: active
$ 
```

**Comment by baentsch** [comment]
The command above is correct and works just fine for me (for both algorithms; for mlkem of course only after [OQS_KEM_ENCODERS](https://github.com/open-quantum-safe/oqs-provider/blob/main/CONFIGURE.md#oqs_kem_encoders) was set when building) and is [even tested](https://github.com/open-quantum-safe/oqs-provider/blob/8cf221760493feaf6a522880b4ccffc8f2446e0d/scripts/oqsprovider-certgen.sh#L34). 

--> some provider interaction problems again? I only had default and oqsprovider active when testing.

**Comment by beldmit** [comment]
https://github.com/open-quantum-safe/oqs-provider/blob/main/CONFIGURE.md#oqs_kem_encoders - I don't see this flag in your build script

**Comment by beldmit** [comment]
Could you please share your configuration? Looks like it is related to https://github.com/openssl/openssl/issues/26038
@simo5 could you please check?

**Comment by simo5** [comment]
Yes sounds like it could be related.
@mouse07410 does the problem go away if you change the pkcs11 provider configuration (just for testing) to enforce early loading of the pkcs11 token ?

**Comment by beldmit** [comment]
Reproduced for Linux, thanks

**Comment by baentsch** [comment]
> Reproduced for Linux, thanks

Trying to get to the bottom of this: Do I get this statement right in that it seems to be a pkcs11provider issue (and further discussions can/do happen on https://github.com/openssl/openssl/issues/26038 and the question here/on oqsprovider is closed for good?)

**Comment by beldmit** [comment]
I think it's an OpenSSL issue because the order of lines in the OpenSSL config matters but there is definitely no problems with oqsprovider.

Sorry for disturbing

**Comment by baentsch** [comment]
> Sorry for disturbing

No disturbance. Just wanted to know where to keep looking - my interest is not limited to oqs...

**Comment by beldmit** [comment]
@mouse07410 For me it works when the PKCS#11 provider is the last. But it is not a fix and even not a workaround
