### ISSUE TITLE
DTLS 1.3 test cases available for testing?

### ISSUE THREAD

**Issue by lakshya-chopra** [open-quantum-safe/oqs-provider#598]
Hello,
The latest addition of `DTLS 1.3` looks really exciting. I tried this update with the OpenSSL's `feature/dtls-1.3` branch, appropriately setting up all the required environment variables. The specific commit I used: [Fix DTLS 1.3 handshake transcript hash](https://github.com/openssl/openssl/commit/debf129adca83bd7deaf862d2c5942133a721e54) .

I ran some tests with this & while the TLS tests completed successfully, the DTLS ones did not run.
Could you confirm whether the DTLS 1.3 test cases are currently implemented and available for testing?

**Comment by baentsch** [comment]
I did run the test on the feature branch and it executed (and passed) DTLS handshake testing. Did you run the "scripts/fullbuild.sh" with the OPENSSL_BRANCH env var suitably set as per comment?

**Comment by lakshya-chopra** [comment]
This did work! I was actually trying some manual compilation of the test cases & might have missed something in that. The pre-defined scripts are running fine though.
Thank you :)
