### ISSUE TITLE
Memory leaks during key creation and signing

### ISSUE THREAD

**Issue by xShuusui** [open-quantum-safe/oqs-provider#92]
Hi, 
we are currently developing a crypto api and found some memory leaks with valgrind during key creation with pqc algorithms.

The leaks we found:
- During `EVP_PKEY_keygen_init` in  **oqs_kmgmt.c**, line 422 
`gctx->oqs_name = OPENSSL_strdup(oqs_name);`
- During `EVP_PKEY_generate` in **oqsprov_keys.c**, line 618
`ret->tls_name = OPENSSL_strdup(tls_name);`
- During `EVP_DigestSignInit` from `ASN1_item_i2d` in **oqs_sig.c**
Not able to fix it, but we assume its coming from line 156: `ctx->aid_len = get_aid(&(ctx->aid), ctx->sig->tls_name);`, from a not correctly freed `aid`.

We started with version *0.4.0* of the oqs-provider, when we saw that there are memory leaks fixed on [commit](https://github.com/levitte/tmp-oqsprov/commit/3d573cc2862c66d513edde21d447692d85678d60), we switched to the current [main](https://github.com/levitte/tmp-oqsprov/commit/277b3719686c16e60c24ad8b4e82f18ec3778a1e) version. The leaks listed above also occurred there.

**Comment by xShuusui** [comment]
Yes, no problem, I will try to fix the last leak and open a pull request.

**Comment by xShuusui** [comment]
@baentsch Do i have the permissions to create a branch in this repository? I have fixed it locally but cannot push it.

**Comment by baentsch** [comment]
Please submit your fixes via PR from your own fork. A nice summary has recently been posted by Thom Wiggers to the oqs-developers mailing list:

> The way PRs work on Github is that you create a copy of a repository under your own account (a so-called fork), add this fork as a "remote" to your local copy of the repository, and then push your changes to the fork under your github account. You can then open a pull request (so-called because it's a request to pull changes from your git repository!) through the command line.
> 
> See also: https://docs.github.com/en/get-started/quickstart/contributing-to-projects
