### ISSUE TITLE
Deploy test server

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-provider#93]
Either replacing or amending test.openquantumsafe.org with an instance running oqs-provider to also test integrations and OpenSSL3. Would also allow implementing https://github.com/open-quantum-safe/openssl/issues/388#issuecomment-1342703151

**Comment by baentsch** [comment]
@bhess As a follow-up to our email conversation I now assigned this to you as I don't have access to the test server any more. Please confirm that you'll be able to have this complete by the end of next week as part of our `liboqs` release (confirmation) cycle.

**Comment by bhess** [comment]
Thanks @baentsch, will look into it next week.

**Comment by bhess** [comment]
Should there be (or is there already something like) a [common.py](https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/oqs-test/common.py) for oqs-provider?
The script for OpenSSL 1.1.1 contains python structures with the available KEMs, Signatures and helper functions to create keys and certs, which is used by the deployment scripts for the test server. The alternative I see is to load generate.yml and create the algorithm list again, but there seems quite some logic involved in `generate.py` that I think is better not to replicate. @baentsch

**Comment by bhess** [comment]
The test server based on liboqs-0.8.0-rc1 is now ready at https://test.openquantumsafe.org.

For now it's based on oqs-provider/main. Will update to a oqs-provider release tag once ready.

I did a test run (https://github.com/open-quantum-safe/oqs-demos/blob/bhe-nginx-serverupd/nginx/fulltest-provider/testrun.sh), and all tests passed.

The ports offered by the test server are now restricted to Signartures+KEMs with matching security levels (exceptions are the pure rsa/ecdsa signatures as baseline).

Not sure if makes sense to advertise the Chromium-ready test ports as there seems to be no build against 0.8.0 at the moment. So I removed the Chromium page for now.

**Comment by baentsch** [comment]
> So I removed the Chromium page for now.

Perfect for me: We're not _really_ supporting it, so we should drop the appearance of that, too.

**Comment by baentsch** [comment]
@bhess: Release is tagged. Will mark final if you can close this issue after correct testing.

**Comment by bhess** [comment]
https://test.openquantumsafe.org is updated with liboqs 0.8.0 and oqs-provider 0.5.0, which includes generating the config using `openssl list`.

After a run with https://github.com/open-quantum-safe/oqs-demos/blob/bhe-nginx-serverupd/nginx/fulltest-provider/testrun.sh and the oqsprovider/curl image, all tests except the new `x25519_kyber768` and `p256_kyber768` hybrids pass. It looks like curl in the image doesn't support them yet. I also built a local version of the curl docker image, there everything works fine.

**Comment by baentsch** [comment]
Thanks for integration and test -- https://github.com/open-quantum-safe/oqs-demos/pull/206 added to fix `curl` docker image for good and https://github.com/open-quantum-safe/oqs-provider/issues/181 to avoid this from happening again. This then closes this issue out.
